### ISSUE TITLE
Scroll bar jumps up when sorting

### ISSUE THREAD

**Issue by FrEaKmAn** [angular-ui/ui-sortable#109]
Hello

When I try to sort, the whole page scrolls up which causes strange experience when sorting. I found

http://stackoverflow.com/questions/1735372/jquery-sortable-list-scroll-bar-jumps-up-when-sorting

Is there a possibility to implement this into ui-sortable?

Thank you

**Comment by thebucknerlife** [comment]
@thgreasi has there been any progress on this? sorry to dig up an old issue but none of the SO solutions (settings height or using a placeholder) have worked for me.

Thanks

**Comment by thgreasi** [comment]
@thebucknerlife since this is marked as a jquery-ui related issue, I didn't put any extra effort on this.
Hopefully some stackoverflow research on jquery-ui-sortable might give you some results.

**Comment by basvandenheuvel** [comment]
Very very very very very very very bad there isn't a good solutions for this yet.

The so called "solution" above is crap if you the draggable items within your sortable do not have the same size, like in my case.

**Comment by mcblum** [comment]
@basvandenheuvel Very very very very very very very bad that you haven't made a solution and submitted a pull request. The dev community does not exist to make your life easy-peasy. Sack up and fix it if you want it fixed.

**Comment by basvandenheuvel** [comment]
@mcblum welcome to github, you must be new around here :) Complaining about stuff does not equal to "i can do it better". Welcome

**Comment by mcblum** [comment]
@basvandenheuvel True, but maybe a little tact would be nice considering you're using something that you didn't pay for. Commenting on a bug, reporting something that doesn't work, all fine. Being a dick, not that cool. Welcome
