### ISSUE TITLE
Prevent ng-click from being called when sorting

### ISSUE THREAD

**Issue by pastinepolenta** [angular-ui/ui-sortable#174]
I have this configuration:

```
<ul ui-sortable="sortableOptions">
   ....
      <a ng-click="doSometing()">
```

when I click on the link it works fine but sometimes the ng-click function is called even after I dragged/sorted. Is there a way to stop ng-click if dragging ?

**Comment by shyr** [comment]
@stilllife00 
> helper : 'clone'

This really works for me in firefox. Thank you
