### ISSUE TITLE
UI sortable & contenteditable div does not work

### ISSUE THREAD

**Issue by asithw** [angular-ui/ui-sortable#188]
when content editable div cannot edit with in  sortable elements

following example cannot edit item name properly  
http://codepen.io/anon/pen/kCfsL

**Comment by renehamburger** [comment]
Related to this issue: it is not possible to enter a contenteditable element within a ui-sortable container with a left click. See http://codepen.io/rh/pen/oXGORP.

It is possible to enter it with tab or a right click.
