### ISSUE TITLE
Updating alternative index value

### ISSUE THREAD

**Issue by geekgonecrazy** [angular-ui/ui-sortable#204]
I've got list with both a track by and and order by on it

```
<ul ui-sortable ng-model="products">
<li ng-repeat="product in products | orderBy: 'listIndex' track by product.listID" ng-controller="product">ID {{product.listIndex}}
</li>
</ul>
```

Then i've got a product controller that will update the server when the product is updated.  I need it to update also when I rearrange.

Previously I had this done just watching for the $index to change.  But with the track by and order by the index value never updates.

I've managed to add sortableOptions to the ui-sortable and get the product i'm dragging to update... but this doesn't work for all of the other ones.

```
$scope.sortableOptions = {
    stop: function(e, ui) {
        var originalIndex = ui.item.sortable.index;
        var newProdArray = ui.item.sortable.resort.$modelValue;

        newProdArray[originalIndex].listIndex = ui.item.index() + 1;
    },
    axis: 'y'
};
```

So how do I either get it to update $index or let me specify what to use as the index?

**Comment by dud3** [comment]
+1
