### ISSUE TITLE
Question: How do you disable the sorting attribute dynamically?

### ISSUE THREAD

**Issue by yahya-uddin** [angular-ui/ui-sortable#241]
I want to be able to diable the sorting attribute if a cetain condition is met (e.g. if the value of a combobox is a cetain value).

For instance if my html is like this:

``` html
 <label >Search: </label>
<input ng-model="query.name"/>

<label>Sort By:</label>
 <select ng-model="orderProp">
            <option value="">Custom</option>
            <option value="name">Alphabetical</option>
            <option value="date">Latest</option>
</select>

<ul ui-sortable="sortableOptions" ng-model="categories">
    <li ng-repeat="category in categories | filter: query | orderBy: orderProp">
        {{ category.name }}
    </li>
</ul>
```

I want the sorting feature to work if the sorting is set to 'custom' and not to work if the sorting feature is anything else.

How would I do this? I know there is a disable feature in the Jquery UI: http://api.jqueryui.com/sortable/#method-disable

Many Thanks for creating a great plugin!

**Comment by aderowbotham** [comment]
@anik786 That works, but why the square brackets / array key syntax? 

`$scope.sortableOptions.disabled = false` works for me.

**Comment by thgreasi** [comment]
@aderowbotham
They are indeed equivalent for that property.
The only property of the options object that I can think that needs the bracket syntax is `ui-float`.

**Comment by pradipgarala** [comment]
$scope.sortableOptions.disabled = false, also worked for me.

**Comment by anik786** [comment]
@aderowbotham edited. good catch
