### ISSUE TITLE
ui-sortable on android?

### ISSUE THREAD

**Issue by it02Inartec** [angular-ui/ui-sortable#249]
Is compatible with android/other plataforms? It runs on android? 
I made a simple application with angularJs and use "ui-sortable" works fine .. but when converti to android, not working. is this possible? or am I doing wrong?

**Comment by ajaiswal595** [comment]
Can any body send me the code snippet.

This is my require js file main.js file . But even it is not working 

/* main.js
*	Requirejs Dependencies shim and dependencies
*/
require.config({
	waitSeconds: 0,
	paths: {
		"angular":"../vendor/angular/angular.min"
		,"jquery":"../vendor/jquery/dist/jquery.min"
	    ,"ui-router":"../vendor/angular-ui-router/release/angular-ui-router.min"
	    ,"ui-bootstrap":"../vendor/angular-bootstrap/ui-bootstrap-tpls.min"
	    ,"angular-animate":"../vendor/angular-animate/angular-animate.min"
	    ,"angular-sanitize":"../vendor/angular-sanitize/angular-sanitize.min"
	    ,"ui-grid":"../vendor/angular-ui-grid/ui-grid.min"
	    ,"ui-select":"../vendor/ui-select/dist/select.min"
	    ,"jquery-ui":"../vendor/jquery-ui/jquery-ui.min"
	    ,"ui-sortable":"../vendor/angular-ui-sortable/sortable.min"
	    **,"touch-punch":"../vendor/touch-punch/touchpunch"**	
	    ,"report-app":"./app"
	},
	shim:{
		"angular":{
			deps:["jquery"],
			exports: "angular"
		},
		"report-app":{
			deps:["angular","ui-router","ui-bootstrap","angular-sanitize","ui-grid","ui-sortable",**"touch-punch"]**
	
		},
		"ui-router":{
			deps:["angular"]
		},
		"ui-bootstrap":{
			deps:["angular"]
		},
		"angular-sanitize":{
			deps: ["angular"]
		},
		"ui-select" : {
				deps: ["angular"]
		},
		"angular-animate":{
			deps:["angular"]
		},
		"ui-grid" : {
			deps:["angular"]
		},
		"ui-sortable" : {
			deps:["angular","jquery-ui"]
		},
		**"touch-punch":{
			deps:["jquery","jquery-ui"]
		}**
	}
});
//Manual bootstrapping the angular application
require(["report-app"],function(app){
	angular.bootstrap(document.getElementById('report-app'),["reportApp"]);
});
