### ISSUE TITLE
How do I get the helper option to work? Especially with "clone".

### ISSUE THREAD

**Issue by yizhao** [angular-ui/ui-sortable#270]
Does this library implement JQuery's native clone feature?

I know there is an example of a "clone" but it doesn't use JQuery's native helper.  It only adds a element back to the original list after it has been dropped.

Here is a plunker: http://plnkr.co/edit/AwdAivvVZcnV9aDxbp7m?p=info

Any advice is appreciated.

**Comment by koolmoo** [comment]
Hi,

Sorry to bring up an old issue, but I was having the same problem and eventually realized that appendTo doesn't work without specifying a helper (other than default). Unfortunately, this wasn't noted anywhere in the jQuery UI docs. Just wanted to confirm this is the expected result, and also to put it on the record for anyone who's new to ui sortable like me.

**Comment by thgreasi** [comment]
Hi there.
That's strange, since sortable.e2e.spec.js has test cases with `helper:
'clone'` used with and without the `appendTo` option! Can you fork one of
the codepen examples found in README to demonstrate your code & issue?

-- 
*Thodoris Greasidis*
