### ISSUE TITLE
Does ui-sortable play nice with ui.bootstrap.accordion?

### ISSUE THREAD

**Issue by pwhipp** [angular-ui/ui-sortable#285]
I'm having trouble getting a sortable accordion to work. I've [created a jsfiddle](http://jsfiddle.net/whippy/bwq82bvs/) illustrating the problem and asked a [question on stackoverflow](http://stackoverflow.com/questions/26520131/how-can-i-create-a-sortable-accordion-with-angularjs) and am raising the issue here in the hope you can help me see why it is not working.

**Comment by thgreasi** [comment]
I liked [this solution](https://stackoverflow.com/questions/26520131/how-can-i-create-a-sortable-accordion-with-angularjs/27637542#27637542) found in your stackoverflow thread.
To ease the tracking of this issue [here is mock of the proposed integration](http://plnkr.co/edit/TGIeeEbbvJwpJ3WRqo2z?p=preview).

**Comment by thgreasi** [comment]
I'm closing this for now,
I hope for a proper in v0.14.x to handle all interactions with directives that do transcludes.
