### ISSUE TITLE
Dragged Item jumps vertically by page scroll amount on first drag only

### ISSUE THREAD

**Issue by julian-iFactory** [angular-ui/ui-sortable#286]
I have an App that is one long scrolling page with an anchor menu that auto scrolls the page similar to http://mgcrea.github.io/angular-strap/

I am using the 'horizontal' mode of ui-sortable with enough items to wrap across three rows.

Angular ui-sortable works perfectly if I load the page and it has not scrolled. If I scroll the page vertically by e.g. 200px then when I first drag a sortable element it jumps down a corresponding 200px until it is dragged over a neighboring item, it then assumes the correct position again. Every subsequent drag and drop works perfectly, even if I scroll the page again there is no vertical jumping of the draggable element by the corresponding amount scrolled.  

I believe the vertical location of the draggable element is being calculated on page load but is not being updated after I have scrolled the page. Once dragging, UI-sortable then manages to rectify itself about the time the 'update' jQuery UI event is broadcast ie after is is over a another element.

Is it possible for me to manually call the method that recalculates the draggable items position, on drag 'start' event?

![angular ui-sortable - jump on vertical scroll issue](https://cloud.githubusercontent.com/assets/4917381/4747302/2e3fb2b8-5a5a-11e4-95d1-c540f55c94ff.jpg)

**Comment by Furg** [comment]
OMG!!! Thanks! I love u dude!! :+1:

**Comment by liadlivnat** [comment]
this is what works for me

```
   $scope.sortableOptions = {
                start: function(e, ui) {
                    $('#sortable-ul-selector-id').sortable({
                            sort: function(event, ui) {
                                var $target = $(event.target);
                                if (!/html|body/i.test($target.offsetParent()[0].tagName)) {
                                    var top = event.pageY - $target.offsetParent().offset().top - (ui.helper.outerHeight(true) / 2);
                                    ui.helper.css({'top' : top + 'px'});
                                }
                            }
                    });

                },
                update: function(e, ui) {
                    if (ui.item.sortable.model.idVideo == -1) {
                        ui.item.sortable.cancel();
                    }
                }
            };
```

**Comment by thgreasi** [comment]
@liadlivnat thanks for the feedback :+1:

**Comment by nickells** [comment]
@julian-iFactory this solution worked for me! It might be slightly more performant to not put firstSort on the $scope though (ie, just `var firstSort`)

**Comment by kakaeriel** [comment]
@nickells try it

``` javascript
        $scope.wscrolltop = '';
        $scope.sortableFirst = false;

        $scope.sortableOptions = {
            'ui-floating': 'auto',
            'start': function (event, ui) {
                if($scope.sortableFirst){
                    $scope.wscrolltop = $(window).scrollTop();
                }
                $scope.sortableFirst = true;
            },
            'sort': function (event, ui) {
                ui.helper.css({'top': ui.position.top + $scope.wscrolltop + 'px'});
            }
        };
```

**Comment by bigdavenr1** [comment]
The parent must have an "overflow: auto". Thats all!

**Comment by ahmerrkhanzz** [comment]
@kakaeriel thanks, it works for me. Love you man.

**Comment by flyher** [comment]
@kakaeriel 
@ahmerrkhanzz 
It doesn't work in first time when i drag,.
And when i set `revert: true`, the `animation effect` show the wrong  position.

**Comment by snowil7** [comment]
It was halped to me:
`
start: function (ev, ui) { 
                let scrollTop = $(window).scrollTop();
                if (scrollTop > 0) {
                    ui.helper.css('margin-top', scrollTop);
                }
            },
            stop: function (ev, ui) {
                ui.item.css('margin-top', 0);
            }
`

**Comment by sn0wil** [comment]
It was useful to me:

```start: function (ev, ui) { 
                let scrollTop = $(window).scrollTop();
                if (scrollTop > 0) {
                   ui.helper.css('margin-top', scrollTop);
                }
            },
            stop: function (ev, ui) {
                ui.item.css('margin-top', 0);
            }```
