### ISSUE TITLE
Publish 0.13.0 to npm

### ISSUE THREAD

**Issue by royaldark** [angular-ui/ui-sortable#298]
0.12.5 is the most recent version in npm.

**Comment by thgreasi** [comment]
@ws-anashkin any feedback?

**Comment by till** [comment]
@thgreasi Any idea what happened to this? There hasn't been a release in a long while. Maybe other people could be added as contributors so they can release on npm? :)

**Comment by thgreasi** [comment]
Unfortunately I'm not a contributor on npm and the initial publisher has
not responsed to me yet.
I have contacted npm describing the situation and we are following the
appropriate procedure, so that I they manually add me as a contributor to
the orphan npm package.

**Comment by thgreasi** [comment]
Currently, we are forced to use bower if we need the latest version of the
package...

**Comment by till** [comment]
@thgreasi Thanks for working on it.

Btw, we are currently using napa to install it.

**Comment by thgreasi** [comment]
As of 2015-05-28 I got access rights to the [npm package](https://www.npmjs.com/package/angular-ui-sortable) and as of 205-06-01 you can find v0.13.3 on npm :)

**Comment by till** [comment]
@thgreasi Thank you! :)
