### ISSUE TITLE
Error: no such method 'instance' for sortable widget instance

### ISSUE THREAD

**Issue by yayolius** [angular-ui/ui-sortable#316]
I don't know why i get that error twice one in line 79 and 226 (current version), with a dinamic loaded list. The weird thing is that the list is still sortable.
Thanks

**Comment by thgreasi** [comment]
What version of jquery-ui are you using?

**Comment by yayolius** [comment]
The last one, that you point in the website

The first error goes in here:


            // When we add or remove elements, we need the sortable to 'refresh'
            // so it can find the new/removed elements.
            scope.$watch('ngModel.length', function() {
              // Timeout to let ng-repeat modify the DOM
              $timeout(function() {
                // ensure that the jquery-ui-sortable widget instance
                // is still bound to the directive's element
                if (!!element.sortable('instance')) {//////HHEEEEEEERREEEEE
                  element.sortable('refresh');
                }
              }, 0, false);


and the second one in here:

            scope.$watch('uiSortable', function(newVal /*, oldVal*/) {
              // ensure that the jquery-ui-sortable widget instance
              // is still bound to the directive's element
              if (!!element.sortable('instance')) {///HEREEEEE

**Comment by thgreasi** [comment]
It looks like the links in the README are for v1.10.x instead of v1.11.x.
The test cases use the latest version (v1.11.x) fetched from bower and that's why I could spot this issue while developing.
I will push a hotfix in the weeken to restore support for jquery-ui v 1.9+ as advertised.

Thanks for your collaboration in this issue.

**Comment by thgreasi** [comment]
Fixed in v0.13.2, releasing now
