### ISSUE TITLE
Cannot read property 'splice' of undefined

### ISSUE THREAD

**Issue by srsgores** [angular-ui/ui-sortable#317]
This directive fails for me, on sort **drop**, using jQuery UI 1.10.3:

> TypeError: Cannot read property 'splice' of undefined
    at http://app/assets/tools/bower_components/angular-ui-sortable/sortable.js:175:38
    at l.$eval (http://app/assets/tools/bower_components/angular/angular.min.js:126:193)
    at l.$apply (http://app/assets/tools/bower_components/angular/angular.min.js:126:419)
    at callbacks.stop (http://app/assets/tools/bower_components/angular-ui-sortable/sortable.js:174:23)
    at HTMLElement.<anonymous> (http://app/assets/tools/bower_components/angular-ui-sortable/sortable.js:21:17)
    at $.Widget._trigger (http://app/templates/template/bower_components/jquery-ui/ui/jquery-ui.js:785:13)
    at $.widget._trigger (http://app/templates/template/bower_components/jquery-ui/ui/jquery-ui.js:4752:35)
    at null._trigger (http://app/templates/template/bower_components/jquery-ui/ui/jquery-ui.js:401:25)
    at $.widget._clear (http://app/templates/template/bower_components/jquery-ui/ui/jquery-ui.js:4743:9)
    at null._clear (http://app/templates/template/bower_components/jquery-ui/ui/jquery-ui.js:401:25)

The error occurs [here](https://github.com/angular-ui/ui-sortable/blob/master/src/sortable.js#L209).

I would appreciate any advice on fixing this (if it's a jQuery UI issue), or else timelines on a fix.

**Comment by srsgores** [comment]
Indeed, it appears that ``modelValue`` is ``null``:

![image](https://cloud.githubusercontent.com/assets/1750837/5766889/02dd8078-9cc2-11e4-8b51-e8e322d06fe2.png)

Is [line 175](https://github.com/angular-ui/ui-sortable/blob/master/src/sortable.js#L209) supposed to "replace" the contents of the swapped elements?  I just looked at the source, and I'm a little confused.  Perhaps I can investigate further...

**Comment by thgreasi** [comment]
Couldn't reproduce and [the tests seem to pass](https://travis-ci.org/angular-ui/ui-sortable/builds/47209971).
Can you provide an example codepen of your usecase/code?

**Comment by thgreasi** [comment]
@srsgores any feedback?

**Comment by thgreasi** [comment]
Is there any chance that your model gets nullified at some point in the lifetime of your application?

**Comment by srsgores** [comment]
@thgreasi, no.  I never reset the model.  

I'm sorry for not responding earlier.

We're using this in a complex page environment, so I'm not sure if I'll get enough time to reproduce.  However, here are the options I'm using (coffeescript):

```
app.controller("MortgageController", function($scope){
	$scope.sortableOptions = {
		activate: function(){
			console.log("Sortable activated");
		},
		beforeStop: function(){
			console.log("Before stop");
		},
		change: function(){
			console.log("change");
		},
		stop: function(e, ui){
			console.log("stopped");
		},
		update: function(e, ui) {
			console.log(e, ui);
		},
		axis: "y"
	}
}
```

And the markup:

```
<section class = "historical-addresses sortable-items ng-pristine ng-untouched ng-valid ui-sortable" ui-sortable = "sortableOptions" ng-model = "historicalAddresses">
	<div class = "historical-address horizontal sortable-item ng-scope" ng-repeat = "address in previousAddresses">
		<span class = "handle" title = "Drag to Re-order"><i class = "icon-menu"></i></span></div>
</section>
```

I get this in my console:

>  Sortable activated
2015-01-19 14:23:28.290MortgageCalculator.coffee:31 change
2015-01-19 14:23:28.666MortgageCalculator.coffee:29 Before stop
2015-01-19 14:23:28.669MortgageCalculator.coffee:35 n.Event Object
2015-01-19 14:23:28.673angular.js:11822 TypeError: Cannot read property 'splice' of undefined

Hopefully this helps.

**Comment by thgreasi** [comment]
You are using `ng-model = "historicalAddresses"` but in the `ng-repeat` I saw that you are using `"address in previousAddresses"`.
Are they equal to each other? README states:
> The items of ng-model must match the indexes of the generated DOM elements.

Any chance you can make a simplified fiddle/pen of your case with some data? Preferably a fork of the simple example found in README.

**Comment by thgreasi** [comment]
@srsgores any feedback on this?

**Comment by srsgores** [comment]
@thgreasi sorry for the delay in responding.  Unfortunately, I will not have the time to do up an example.  However, I have provided you with the information needed, so I would appreciate any efforts to recreate the error.

**Comment by thgreasi** [comment]
A common source of problems is using different models for `ng-model` and `ng-repeat`.
> You are using ng-model = "historicalAddresses" but in the ng-repeat I saw that you are using "address in previousAddresses".

Did you tried using the same variable for both of them?

This is all I can say for now. It most likely has to do with the way you populate your `ng-model` and `ng-repeat` models.
Since this is not described in this issue report, I can't really provide any extra hints/help. It would also be helpful if you could provide the version of angularjs and ui-sortable you are using.

As I told earlier:
> Couldn't reproduce and the [tests seem to pass](https://travis-ci.org/angular-ui/ui-sortable).

Feel free to re-open this issue in case you get some extra time and can provide some extra info.

**Comment by srsgores** [comment]
@thgreasi, indeed, changing my ``ng-model="historicalAddresses"`` to ``ng-model="previousAddresses"`` fixed my issue :)

**Comment by thgreasi** [comment]
:+1:

**Comment by seaBubble** [comment]
Hi,

I am getting the same error, in my case I am trying to drop the item to a new empty list, so the model is empty when the item is dropped.

Any ideas?

Thanks,

**Comment by thgreasi** [comment]
Hi there.
Just make sure that you initialize your model to an empty array and that it's not undefined/null when you start the sorting. You can add a console.log in your start or update callback for that.
