### ISSUE TITLE
Scrollbar causes offset on drag

### ISSUE THREAD

**Issue by morfin** [angular-ui/ui-sortable#318]
Please see picture, exact same problem when scrolling:
http://i.imgur.com/phYGO.gif

It happens on:
Google Chrome Version 39.0.2171.95 (64-bit), OSX Yosemite

Works perfectly on Firefox.

**Comment by thgreasi** [comment]
This looks like a jquery-ui issue, since ui-sortable does not manipulate the DOM elements and just hooks up to the events available to properly update the provided model.

This might also be related to #286, so you might want to try the workaround described there.

Thanks for this awesome report and for your effort creating this gif.

**Comment by morfin** [comment]
Thanks, I will check that. BTW, the image was taken from a different bug report on stackoverflow :)

**Comment by Darex1991** [comment]
@thgreasi bug still exist and it's not the same #286. I had the same problem here [link](https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/examples/jquery_ui_sortable_example.html). Please reopen issue.

**Comment by thgreasi** [comment]
@Darex1991 this is marked as a jquery-ui related issue and that was the reason that it was closed.
There possibly nothing that we can do in the angular side and such discussion should be moved to the related jquery-ui project.

**Comment by Darex1991** [comment]
It's possible to create that topic there by you?

**Comment by thgreasi** [comment]
I'm currently struggling to release v1.4 of this package and also complete the [angular 2 migration](https://github.com/angular-ui/ui-sortable/tree/ng2).
I'm sure that there are available resources on stackoverflow for this jquery-ui related issue/use case.

**Comment by Darex1991** [comment]
Ok I will check it ;) Good luck.

**Comment by benag** [comment]
Hi,
I have the same issue.
Any progress on this?
Ben

**Comment by Darex1991** [comment]
Nope ;(

**Comment by benag** [comment]
@Darex1991 
Did you try manipulate CursorAt, from inside the directive?

**Comment by Darex1991** [comment]
I don't remember :/ I check a lot properties. Try it.

**Comment by clll7** [comment]
I also have this problem everytime I use.   TAT

**Comment by kakaeriel** [comment]
Try it..

``` javascript
        $scope.wscrolltop = '';
        $scope.sortableFirst = false;

        $scope.sortableOptions = {
            'ui-floating': 'auto',
            'start': function (event, ui) {
                if($scope.sortableFirst){
                    $scope.wscrolltop = $(window).scrollTop();
                }
                $scope.sortableFirst = true;
            },
            'sort': function (event, ui) {
                ui.helper.css({'top': ui.position.top + $scope.wscrolltop + 'px'});
            }
        };
```

**Comment by jimgeiger** [comment]
Thanks a lot for the idea @kakaeriel, it helped resolve my problem in the context of an angular/ngRepeat.  I made one adjustment which is to subtract the "$scope.wscrolltop" rather than add.  And obviously if you're scrolling the parent div then use that instead 'window'.  I appreciate the help!

**Comment by amitsingh0542** [comment]
I still have the same issue as @morfin have. Can someone help me to fix this issue?

**Comment by IsraelSistemas** [comment]
@amitsingh0542 get the scrolltop with jquery and substract it from helper ui top

e.g:    ui.helper.css("top", ui.helper.position.top() - $("body, html").scrollTop());

**Comment by jbanulso** [comment]
@IsraelSistemas I think the right code would be `ui.helper.position().top`?

I solved this issue some weeks ago by changing all the ancestors with `position: relative` to `position: static`, and then recalculating the positions with `ui.item.sortable.source.sortable('refresh')`. All this in the "activate" method.

Interestingly enough, after updating Chrome to v62.0.3202.94 today, that fix has stopped working... any ideas?
