### ISSUE TITLE
drop into dragable

### ISSUE THREAD

**Issue by kikko088** [angular-ui/ui-sortable#321]
I create a little file manager, file+folder, I need to drag a file into a folderm putting the file inside the folder, so after release the file this need to disappear and I need to do an ajax call for edit my db.
I do this with jquery ui and all work, now from 2 day I start using angular and I want to create the same thing with angular.

this is my code:

```
        <ul class="files" ui-sortable="sortableOptions" ng-model="files">
            <li ng-repeat="(id,f) in files | filter:query" ng-click="clicked(id)" id="{{f.id}}" file-directive  ng-switch="f.is_folder">
                <div class="file" ng-switch-when='0' >
                    <img class="image" ng-src="{{f.path}}"/>
                    {{f.id}}
                </div>
                <div class="folder" ng-switch-when='1'>
                    <img class="image" ng-src="{{f.path}}"/>
                    {{f.id}}
                </div>
            </li>
        </ul>

```
I don't understant how can I handle the drop, I want to drag only the file div and drop the folder div, how can I do this?

**Comment by thgreasi** [comment]
This directive was intended to handle sortings of items and not the draggable and droppable interactions.
On the other hand, it seems that a drop area is just an empty connected sortable. You should then be able to provide a custom `stop` event handler on the folder sortable, to initiate the ajax call.

Take a look at the "Tree with dynamic template" example in the README. It's the most suitable example I can point you to.

Keep in mind that for your use case, the dynamic templates part might be an overkill. You should only need one level of nesting inside the folder item off your ng-switch.
