### ISSUE TITLE
Show connected list when start dragging

### ISSUE THREAD

**Issue by BramVercaigne** [angular-ui/ui-sortable#324]
I'm trying to make my connected list / dropzone visible when I start dragging an item. When the item is dropped, the dropzone should hide again. (Just one way)
So on my `start` and `stop` conditions, I change a boolean and with that boolean, I hide and show the dropzone with angular css (ng-style or ng-class). 

I'm trying 2 different approaches, but none of them works. 
On my first approach, the dropzone has a height of 0px. When I start dragging, I change the height to 100px. This works, but the item is only recognised if I drag on top of the dropzone. Maybe because the height was 0px on initialising, it remembers the original hight, and only the first pixel is droppable.. If I try to drop in the other 99 pixels, the drop target `ui.item.sortable.droptarget` is undefined. 

On my second approach (that is commented in my codePen) I'm working with the hidden class of bootstrap. But this gives me the same issue.

So if you drag to the top of the dropzone, it works...

Here is my codepen: http://codepen.io/anon/pen/EaXyvB

Maybe i'm doing something wrong with the css of the dropzone? Or is this a familiar issue?

**Comment by thgreasi** [comment]
I gave some effort on this, and [here is the result](http://codepen.io/anon/pen/bNRgER).
Placing the `<h3>` inside the sortable element is a no-no. An empty or css-hided ng-repeat will do the job.

In order to make a text appear inside the sortable element I would sugger you to use:
* CSS :after/:before in combination with [css content](https://developer.mozilla.org/en-US/docs/Web/CSS/content) or
* Some relative/absolute placing for the `<h3>`

Is this sufficient for your use case?

**Comment by BramVercaigne** [comment]
Yes, this is the answer I was looking for!

Thanks for your hint with the css, I use a background image so that's fine. 

I saw that `$('.dropzone').sortable('refresh');` was the thing I was looking for and did the work!

Thank you!!

**Comment by thgreasi** [comment]
Glad it worked for you!
I'm thinking of modifying your pen and adding it to README.
It should be useful for newcomers.

**Comment by BramVercaigne** [comment]
That sounds great! 

[I updated mine also a little bit.](http://codepen.io/anon/pen/PwjRRj)
I used ng-show in stead of playing with the height of the dropzone and added some css.
Thanks for your feedback!

**Comment by thgreasi** [comment]
@BramVercaigne added a drop zone example to README (941dfb0c3918b67127f72e2c62b96f117ef61053).
Thanks very much for your collaboration on this issue!
