### ISSUE TITLE
Add docs for placeholder

### ISSUE THREAD

**Issue by srsgores** [angular-ui/ui-sortable#325]
It's not listed in the docs anywhere, but should be: to override the default ``.ui-sortable-placeholder`` class, you can set the ``placeholder`` property on ``sortableOptions``:

```
$scope.sortableOptions = {
    // ...
    placeholder: "sortable-placeholder"
}
```

**Comment by thgreasi** [comment]
I think it's covered by the first statement in the `Options` paragraph of README:
> All the [jQueryUI Sortable options](http://api.jqueryui.com/sortable/) can be passed through the directive.

I would prefer not to duplicate the jquery-ui-sortable documentation for this project. As a result, the current README only contains the extra parts that this directive supports/adds.
