### ISSUE TITLE
Unable to restrict the draggable object to a specific area?

### ISSUE THREAD

**Issue by jyotirmoypan** [angular-ui/ui-sortable#326]
I would like to restrict the draggable object i.e. table row or list element to a specific area. For example while sorting rows I would like to make sure while dragging rows I cannot drag it beyond the table area. In the implementation part I found it can be dragged beyond the page both horizontally and vertically. Can this be made possible?

**Comment by thgreasi** [comment]
This is a jquery-ui specific question.
I think that the [containment option](http://api.jqueryui.com/sortable/#option-containment) should work for your use case.
