### ISSUE TITLE
Placeholder support

### ISSUE THREAD

**Issue by Kuzmin** [angular-ui/ui-sortable#327]
It would be neat if you could have a placeholder HTML element that appeared at the position that your dragged item would land at if you dropped it.

The best explanation is probably; "I want this behaviour": 
![screen shot 2015-02-02 at 08 33 08](https://cloud.githubusercontent.com/assets/773926/5997068/3372bb20-aab6-11e4-9a90-7f8bc2559799.png)

I think that this should already be possible, since your examples are using something similar, but I can't find documentation for it.

**Comment by thgreasi** [comment]
The README states that [All the jQueryUI Sortable options can be passed through the directive](https://github.com/angular-ui/ui-sortable#options).
You already can use the [placeholder jquery-ui option](http://api.jqueryui.com/sortable/#option-placeholder).

**Comment by Kuzmin** [comment]
Welp, that's embarassing. Sorry!

**Comment by thgreasi** [comment]
Np gl hf!
