### ISSUE TITLE
ui.item.scope().item undefined

### ISSUE THREAD

**Issue by edamron** [angular-ui/ui-sortable#329]
I'm attempting to determine which item on scope was cancelled, using the example on the github page, but 'scope()' is always undefined:

$scope.sortableOptions = {
  update: function(e, ui) {
    // "scope()" below is always undefined
    if (ui.item.scope().item == "can't be moved") {
      ui.item.sortable.cancel();
    }
  }
};

What am I doing wrong?

Thanks

**Comment by ilyadoroshin** [comment]
+1

**Comment by thgreasi** [comment]
Try using `ui.item.sortable.model`.
What version of angular & ui-sortable are you using? Do you also use
debugInfoEnabled(false)?

**Comment by edamron** [comment]
'ui.item.sortable.model' works perfectly!!  This gives me a direct reference to the item on scope that was moved to another position.

Thanks!!

**Comment by thgreasi** [comment]
> Do you also use debugInfoEnabled(false)?

I will update README and the code examples and close this issue.

**Comment by edamron** [comment]
I have used both debugInfoEnabled(false) and debugInfoEnabled(true) in my current app.  At the moment, it's set to true.

Thanks again.

**Comment by thgreasi** [comment]
Closed by 0ef26b63f0379616c60bfe2d66ccc6a196cb6066
