### ISSUE TITLE
Infinite digest loop when using appendTo option with non-string value

### ISSUE THREAD

**Issue by iamchairs** [angular-ui/ui-sortable#330]
Example JSBin:

http://jsbin.com/loqepiyasa/2/edit?html,js,console,output

Steps to reproduce:

* Create a table.
* Make the table head cells sortable with ui-sortable.
* Point the ng-model to an array of cell name to sort.
* In the sortable options passed to ui-sortable add  { appendTo: [any non-string. i.e. document.body] }

The problem actually goes away if you remove ng-model but obviously we'd like to use ng-model.

```
<div id="container" ng-controller="TestSortCtrl">
      <table>
        <thead>
          <tr ui-sortable="sortOptions" ng-model="numbers">
            <th ng-repeat="number in numbers">{{number}}</th>
          </tr>
        </thead>
      </table>
    </div>
```
```
.controller('TestSortCtrl', function($scope) {
  $scope.numbers = [1, 2, 3];
  $scope.sortOptions = {
    axis: 'x',
    items: 'th',
    helper: function(evt) {
      var target = angular.element(evt.target);
      var clone = target.clone();
      clone.css('top', target.position().top);
      return clone;
    },
    distance: 15,
    appendTo: document.body // remove this line and the issue goes away
  };
});
```

**Comment by thgreasi** [comment]
This is strange!?
When using a css selector (`appendTo: 'body'` in your case) [it works fine](http://jsbin.com/lajokeyiji/2/edit).

When changing to an `element` or a `jQuery` object the e2e tests cases fail as well.
Interestingly enough, I can't locate a piece of code in the source that conflicts with this type of `appendTo`.

**Comment by iamchairs** [comment]
I actually found the issue is with angular.js

https://github.com/angular/angular.js/issues/11001

Of they can't/won't fix this maybe you can update this (or I can do a PR) to take the deep watch off the sortable options?

**Comment by thgreasi** [comment]
Changing [$watch to a $watchCollection seems to fix the problem](http://jsbin.com/noyakozado/3/edit).
Although this would drop support for AngularJS version < 1.2

**Comment by iamchairs** [comment]
I'm making a PR to fix the problem in angular. No need to drop support.

**Comment by iamchairs** [comment]
This will fix it. Sorry I made this *your* bug when it's a bug in angular.

https://github.com/angular/angular.js/pull/11006/files

**Comment by iamchairs** [comment]
Per this discussion thread-

https://github.com/angular/angular.js/issues/11001#issuecomment-73416405

Angular.js team isn't going to fix the bug or merge my PR. They said you need to use $watchCollection or format logic differently. What do you think?

**Comment by thgreasi** [comment]
I might can use [a part of this](https://github.com/thgreasi/ng-watchcollection-polyfill) :).
Was thinking of moving to `$watchCollection` for some time now anyway.

**Comment by iamchairs** [comment]
Is the backport important? We need this update today so I can work on the PR if it's all the same.

**Comment by thgreasi** [comment]
What if I created a v0.14.x-dev  branch.
Are you allowed to use this on your production server's bower.json ?

**Comment by iamchairs** [comment]
Yes! That would work for us until 0.14.x is released.

**Comment by iamchairs** [comment]
Just copied that unit test and changed the appendTo to document.body. Works fine, however another unit test is broken.

` uiSortable Nested sortables related should update model when sorting between nested sortables FAILED`

Switched to master to make sure it wasn't a change I made and it looks like it was broken when I pulled it down.

**Comment by thgreasi** [comment]
Fixed in v0.14 by #333

**Comment by auty** [comment]
I was having the same issue. The branch v0.14 solved it. Thanks the the fix.

**Comment by thgreasi** [comment]
Nice to hear that.
We should probably move v0.14 into master. I will try to do it during the
weekend.

On Tue, Oct 13, 2015, 06:18 auty <notifications@github.com> wrote:

> I was having the same issue. The branch v0.14 solved it. Thanks the the
> fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/330#issuecomment-147583668>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by auty** [comment]
+1
