### ISSUE TITLE
How can I prevent an item to be inserted at a certain position?

### ISSUE THREAD

**Issue by burzum** [angular-ui/ui-sortable#331]
I need to disable the ability to move an item to the first or second position of the index and could not yet figure out how to do it.

I can't figure out how to get the last AND new position and also it looks like I can't call cancel() in the stop() callback.

Any guide on this please? Or is it a missing feature?

**Comment by thgreasi** [comment]
As noted in README.md, `ui.item.sortable.cancel()` should be called inside
the `update` callback.
In the API.md you can find the documentation for the extra properties
available through `ui.item.sortable`, one of them is `dropindex`. I think
that this is what you are searching for.

Please feel free to reopen this issue along with a code example in case you
still have problems with your use case.
