### ISSUE TITLE
Having multiple ui-sortable elements within a controller, how to determine current model inside the stop handler ?

### ISSUE THREAD

**Issue by rivaros** [angular-ui/ui-sortable#337]
Imagine we have several ui-sortable elements on page, which use different models within same controller:
```html
<div ng-controller="MyCtrl">
<ul id="sortable1" ui-sortable="sortableOptions" ng-model="model1">
    <li ng-repeat="item in model1">
           {{ item.name }}
    </li>
</ul>
<ul id="sortable2" ui-sortable="sortableOptions" ng-model="model2">
    <li ng-repeat="item in model2">
           {{ item.name }}
    </li>
</ul>
</div>
```

What is the correct way to access the current model inside the stop event-handler
```javascript
app.controller('MyCtrl', ['$scope', function($scope) {
    $scope.sortableOptions = {
        axis: 'y',
        stop: function(e, ui) {
            //This gives us the current item scope, yes
            //But how do we know that we are now moving items in model1 and not in model2, for example?
            ui.item.scope();
           
        }
    };
}]);
```

This might be some core Angular question, but I got stuck on it, and would appreciate your help.

**Comment by thgreasi** [comment]
Take a look at [the AI.md](https://github.com/angular-ui/ui-sortable/blob/master/API.md).
I think that `ui.item.sortable.model` is what you are looking for.

**Comment by thgreasi** [comment]
Also, have a great weekend :)

**Comment by rivaros** [comment]
@thgreasi, you are great. Many thanks.

**Comment by rivaros** [comment]
great weekend to you as well

**Comment by rivaros** [comment]
@thgreasi , sorry, small remark here
ui.item.sortable.model is actually pointing to a single element (the li item which was moved), it is not pointing to original model passed to ul (which was actually an array of items). so this remains a problem.

All the best anyway.

**Comment by thgreasi** [comment]
Ooooops! My mistake, use [droptargetmodel](https://github.com/angular-ui/ui-sortable/blob/master/API.md#droptargetmodel).

**Comment by thgreasi** [comment]
OOOOOOOOoops again....
[sourcemodel](https://github.com/angular-ui/ui-sortable/blob/master/API.md#sourcemodel) it is!

**Comment by rivaros** [comment]
YYES, that was it. Thanks again.
