### ISSUE TITLE
Creating a list of elements with disabled sortables

### ISSUE THREAD

**Issue by RohanPrabhuNomadly** [angular-ui/ui-sortable#338]
I needed to create a list that cannot sort the first or last element in a list and everything else is sortable. I just forked one of your codepens and got this: http://codepen.io/anon/pen/KwREpx

Creating this issue in case you feel you can mention it somewhere where it might be helpful to others. Great work on this library, btw. It works like a charm!

**Comment by thgreasi** [comment]
Thanks :+1:
Similar pens have been available in other issues but never thought about adding them to README.
Thanks again.
