### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by zbend** [angular-ui/ui-sortable#339]
Are there Typescript definitions available? Thanks.

**Comment by thgreasi** [comment]
No, as far as I know, not yet :(
You are the first to start such a discussion here :+1:.

**Comment by jayoungers** [comment]
I came here looking for the same.

For now I'm just using the standard jquery ui interfaces (i.e. `JQueryUI.SortableEvents`), and just marking the fields specific to this implementation as `<any>`

**Comment by thgreasi** [comment]
I guess that these are some good starting points for someone willing to
create a definition file for this repo:
*
https://github.com/borisyankov/DefinitelyTyped/blob/master/jqueryui/jqueryui.d.ts#L638-697
*
https://github.com/borisyankov/DefinitelyTyped/blob/master/jqueryui/jqueryui.d.ts#L1653-1663
* https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-ui

**Comment by thgreasi** [comment]
I created [a fork of DefinitelyTyped](https://github.com/thgreasi/DefinitelyTyped) to do some experimentation on this.
[Here a simple definition file](https://github.com/thgreasi/DefinitelyTyped/blob/master/angular-ui/angular-ui-sortable.d.ts) I ended up.

**Comment by thgreasi** [comment]
I also created [a branch of ui-sortable with a demo.ts file](https://github.com/thgreasi/ui-sortable/blob/TypeScriptTests/demo/demo.ts).
Please provide some feedback.

**Comment by thgreasi** [comment]
Just opened a PR borisyankov/DefinitelyTyped#3827.

**Comment by thgreasi** [comment]
Resolved by borisyankov/DefinitelyTyped#3827

**Comment by jayoungers** [comment]
Nice, thanks @thgreasi !  It looks like it's already showing up in the nuget package w/ ui-router (angular-ui.TypeScript.DefinitelyTyped)

I was going to say I think we're missing a 'resort' property on UISortableProperties, but it looks like I was using an older version of the library.  Outside of that, I'm having some issues getting my solution to compile with the definition file; I'll report back once I figure out what's going on:

![image](https://cloud.githubusercontent.com/assets/6578515/6556034/b754b388-c638-11e4-8531-4ddbd31926d2.png)

**Comment by thgreasi** [comment]
I saw that problem too while writing the test cases. But as you can see [in my branch of ui-sortable](https://github.com/thgreasi/ui-sortable/blob/TypeScriptTests/demo/demo.ts) I didn't reference jqueryui.d.ts and everything was fine.

Is the reference to jqueryui.d.ts in the file that contains the sortable controller necessary?
I would recommend you to refactor your code, so that the controller that contains the sortableOptions objects is in a separate file that does not reference to jqueryui.d.ts.

**Comment by jayoungers** [comment]
No, the reference wouldn't be necessary for this particular file, which would resolve my issue, although I imagine others might run into this as well.

Although it would be a breaking change, it might be a good idea at some point to consider if that property can be renamed, so it's not conflicting with the jqueryui piece

**Comment by thgreasi** [comment]
It might be a good chance to also rename some property names.
