### ISSUE TITLE
Extra properties on "sortable" are all undefined.

### ISSUE THREAD

**Issue by mattwelch** [angular-ui/ui-sortable#340]
No matter what I try, I always get "undefined" for all of the extra properties (noted in API.md) on sortable. This is for update, receive, stop, etc. I've tried older versions of ui-sortable, with the same results.

**Comment by thgreasi** [comment]
Try using one of the provided examples as a starting point.
If you can fork and share an example that looks like your use case, then I
would be happy to investigate it.

**Comment by mattwelch** [comment]
Sorry. I should have provided that from the start. In fact, it would have saved my a post, and you a reply, as I found my problem in the process of providing an example. The shelf life of the object is much shorted than my console.logs was displaying. Thanks for the help.

**Comment by thgreasi** [comment]
Np, happy the examples helped you ;-)
