### ISSUE TITLE
Everything in ui.item.sortable is undefined.

### ISSUE THREAD

**Issue by LordWingZero** [angular-ui/ui-sortable#346]
![Image of problem](http://i.imgur.com/8U78Q4f.png)

```html
    <tbody ui-sortable="vm.sortableOptions" ng-model="vm.plans">
        <tr ng-repeat="plan in vm.plans">
```

``` javascript
    var sortableOptions = {
        placeholder: 'row-placeholder',
        cancel: ".blank-row",
        update: sortableUpdate
    };

    vm.sortableOptions = sortableOptions;
```

**Comment by thgreasi** [comment]
Can you provide a codepen example that demonstrates your use case?
Keep in mind that the properties of ui.item.sortable object are cleared
right after the stop callback fires. (To avoid memory leaks.)

If you need those references you should keep them in variables in your code.

**Comment by LordWingZero** [comment]
That makes sense.

So what callback can I use to see what two models switched places?

**Comment by thgreasi** [comment]
I would suggest you to use either update or stop.
