### ISSUE TITLE
Is there some way to grab the item im switching places with?

### ISSUE THREAD

**Issue by LordWingZero** [angular-ui/ui-sortable#347]
I assume the item in ui.sortable.item.modal is the item im dropping. But how do I get the item that just took the place of the one I am dropping?

**Comment by thgreasi** [comment]
I guess that inside the update callback you could do something like:
```js
var droppedAboveModel;
if ('moved' in ui.item.sortable && ui.item.sortable.index < ui.item.sortable.dropindex) {
    droppedAboveModel = ui.item.sortable.droptargetModel[ui.item.sortable.dropindex - 1];
} else {
    droppedAboveModel = ui.item.sortable.droptargetModel[ui.item.sortable.dropindex];
}
```

**Comment by LordWingZero** [comment]
Whats the difference between droptargetModel and Model?

**Comment by thgreasi** [comment]
The model property holds the object that was used by the ng-repeat to
generate the dragged item.
The droptargetModel property should be the list of objects that is used by
the sortable that the dragged item was dropped into (as assigned to
ng-model/ng-repeat).

**Comment by thgreasi** [comment]
I'm closing this for now. In any case feel free to reopen!
