### ISSUE TITLE
Going vertically down doesn't work most of the time, but going up does work always

### ISSUE THREAD

**Issue by olso** [angular-ui/ui-sortable#355]
I made a  quick video explaining it https://www.youtube.com/watch?v=daDg6CSg6tc

**Comment by olso** [comment]
I guess it must have something to do with modal and bootstrap. Because when I drag it completely out of modal it moves. There must be error with element size calculation. I've tried both tolerance: interest and pointer.

**Comment by olso** [comment]
Turns out that I had to play with the settings first...

```javascript
function createListOptions(placeholder, handle, items) {
    return {
        tolerance: 'pointer',
        items: items,
        helper: 'clone',
        forcePlaceholderSize: true,
        forceHelperSize: true,
        axis: 'y',
        opacity: 0.5,
        zIndex: 9999,
        handle: handle,
        placeholder: placeholder
    };
}
```

**Comment by thgreasi** [comment]
Sorry I have yet to do a research on this. I'm on a limited connection
weekend away from home.
I will give it a look during this week.

I'm glad you found a way to make it work.

**Comment by thgreasi** [comment]
Glad you found an elegant solution for your use case.
:+1: for leaving such a detailed feedback in the repo.
