### ISSUE TITLE
The element doesn't come to the last when drop it at the end of the list

### ISSUE THREAD

**Issue by siliconprime-chuongtran** [angular-ui/ui-sortable#357]
On this demo: 
http://codepen.io/thgreasi/pen/LVVJgK

When i drag an element and drop it on the end of the dropable box, the element doesn't come to the last spot, it goes to the pre-last position.

http://screencast.com/t/USnenMUMHz

Hope it makes sense and sorry for my bad English :)

Thanks
#306

**Comment by thgreasi** [comment]
Thanks for this detailed report. There is obviously a dislike for the last place by jquery-ui.
Unfortunately this is just a repetition of #306.
Since this is reproducable without angularjs please fill a bug report in jquery-ui bugzilla.

**Comment by thgreasi** [comment]
Such problems, with side-by-side `ui-sortable`s, happened to me as well while writing the e2e test of this repo.
I feel bad that there is not even a good workaround reported in this repo.

**Comment by RMarinaro** [comment]
Looks like jquery-UI 1.11.4 and 1.12.1 both addressed this, upgrading to those versions fixed this for me.

**Comment by thgreasi** [comment]
Great, thanks for the feedback!

-- 
*Thodoris Greasidis*
