### ISSUE TITLE
ngModel is null

### ISSUE THREAD

**Issue by davidhartman** [angular-ui/ui-sortable#362]
Whenever I have more than one item in my list and reorder it, I get ngModel is null error. Am I doing something wrong?

here is my plunker. Just click the load button twice and reorder the div's and you'll see the error:

http://plnkr.co/edit/BCmS73Qzm5w3lM9R3MP5?p=preview

**Comment by davidhartman** [comment]
It appears to be around the "items" in the sortableOptions object. If I don't add the items attribute, everything works fine.

**Comment by davidhartman** [comment]
Sorry not a bug at all ... just didn't have my selector and handle configured correctly.

**Comment by Darex1991** [comment]
@davidhartman please share difference in your code ;)

**Comment by Darex1991** [comment]
Ok for everyone.. I found when it's buggy.
When you're using parameter `items`.
Without that everything should work correctly ;)

**Comment by thgreasi** [comment]
Can you shade a codepen example?

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by Darex1991** [comment]
@thgreasi you can open @davidhartman example (http://plnkr.co/edit/BCmS73Qzm5w3lM9R3MP5?p=preview) and then remove parameter `items` from his `controller.js` file.

**Comment by thgreasi** [comment]
The `items` selector should target an immediate child element of the `ui-sortable` directive (in other words the [ng-repeat] elements). eg: `items: '> .mySortableItemRepeater'`
In that example, the targeted element is actually several levels deeper: `[ui-sortable] > [ng-repeat] isolated > .sortable`.

**Comment by Darex1991** [comment]
@thgreasi Oooo. I will check it and write it here immediately how it's works ;)

**Comment by Darex1991** [comment]
@thgreasi Hmm probably you have rights ;)
