### ISSUE TITLE
Sorting direction

### ISSUE THREAD

**Issue by Chris159** [angular-ui/ui-sortable#363]
Hi, I'm trying to sort my object and set a fieldOrder in my for Loop. I have two rows. Everything works fine, if I drag my last element to the first one. If I try to drag the first after the last one, my model do not Change...
vm.sortableOptions = {
                stop: function(e, ui) {
                    console.log("Sort");
                    for (var index in vm.bdConfigTable.bdConfigTableFields) {
                        $scope.safeApply(function() {
                            vm.bdConfigTable.bdConfigTableFields[index].fieldOrder = index;
                        });
                    }
                },
                'ui-floating': false
            };

**Comment by thgreasi** [comment]
Can you provide an example by forking one of the two "Ordering" examples found in README?

**Comment by thgreasi** [comment]
Any feedback on this?
As noted in the README examples & details link, you should do the sorting inside the controller and not in the view (the `ng-repeat`).
Is this the case?

**Comment by thgreasi** [comment]
> Any feedback on this?

I'm closing this for now.
Feel free to re-open, if you still have problems.
