### ISSUE TITLE
Asynchronous loading of jQuery and jQuery UI

### ISSUE THREAD

**Issue by crisbeto** [angular-ui/ui-sortable#364]
jQuery and jQuery UI can be pretty large and a burden to load on every page, if Sortable is only being used on a single page. I have a solution that loads the libraries asynchronously, only when a sortable directive is encountered. Would it be of interest to submit a PR for this feature?

**Comment by thgreasi** [comment]
I would be very interested to take a look at an example pen and possibly
add a reference into README.
What do you mean with "every page"?
If ui-sortable is defined as a module of an angular app, then jquery &
jquery-ui should be already loaded. To be precise, jquery should be loaded
before angular itself (except if you are manually patching angular.element).

Since ui-sortable js file is loaded after angular, how this solution works?

**Comment by crisbeto** [comment]
It loads jQuery and jQuery UI when the `link` function of sortable is executed. It doesn't seem to be a problem that jQuery is loaded after Angular has been bootstrapped (albeit I'm not sure if Angular uses it at this point), the Sortable works fine and it hasn't given me any trouble (I've been using this method for about a year now). Keep in mind that no other parts of my app depend on jQuery and I don't know what would happen if they did. Here's the monkey patch I did to defer the Sortable directive:

```
angular.module('ui.sortable').config(['$provide', function($provide) {
    $provide.decorator('uiSortableDirective', ['$delegate', '$window', 'utilities', function($delegate, $window, utilities){
        var directive = $delegate[0];
        var link = directive.link;

        directive.compile = function(){
            return function(){
                var args = arguments;
                var dis = this;

                utilities.loadDependency('js/lib/jquery-1.9.0.min.js').then(function(){
                    utilities.loadDependency('js/lib/jquery-ui.min.js').then(function(){
                        angular.element.fn = angular.element.fn || $window.jQuery.fn;
                        angular.element.fn.jquery = angular.element.fn.jquery || $window.jQuery;

                        // 0 is the scope, 1 is the element
                        args[1] = $(args[1]);

                        link.apply(dis, args);
                    });
                });
            };
        };

        return $delegate;
    }]);
}]);
```

If necessary I can include the `utilities` service that loads the script, but it basically just inserts a script tag, binds a `load` listener and returns a promise that gets resolved when `load` is fired.

**Comment by thgreasi** [comment]
I was thinking of adding an extra property like ui-module-link to the
options object, that would accept a callback, that could optionally return
a thenable.
The decorators seem to work fine :+1: though.
It would be great if you could fork one of the codepens found in README and
apply your use case. I would then be more than happy to review and merge a
PR adding this example right next the requirejs example link.

**Comment by crisbeto** [comment]
Sure thing. I was thinking that it would be a cool feature to add to the module itself, although it could be considered an edge case.

**Comment by thgreasi** [comment]
Any feedback on this?
Have you been able to mock an example to add in README?

**Comment by crisbeto** [comment]
Ah sorry, I've been busy recently. I've added it to my list.

**Comment by crisbeto** [comment]
@thgreasi I made it into an [addon](https://github.com/crisbeto/angular-ui-sortable-loader) so its a little bit more reusable. Here's a link to the demo, if you want to include it in the examples: http://crisbeto.github.io/angular-ui-sortable-loader/

**Comment by thgreasi** [comment]
:+1: will add a link in README as soon as I'm home.
