### ISSUE TITLE
Add a license header 

### ISSUE THREAD

**Issue by lkiesow** [angular-ui/ui-sortable#366]
When dealing with a lot of libraries in larger FOSS projects it is hard to keep track of the origin and license of each external library. Having a short header stating the license, origin (and maybe version) makes things a lot easier. I would greatly appriciate it if you could add such a header.

Something like:

    /**
     * UI.Sortable <VERSION>
     * https://github.com/angular-ui/ui-sortable
     * Copyright (c) 2012 the AngularUI Team, http://angular-ui.github.com
     * MIT License
     */

Of course, while having the `<VERSION>`in this as well would be really nice, it only makes sense to add this if it is updated regularly. If not, it is better to leave it out.

**Comment by thgreasi** [comment]
You are right.
We should add it to the `banner` section of the `build` & `publish` step.
This will add it to the files generated in the `dist` folder and the bower package etc without adding it to the `src` files.

**Comment by thgreasi** [comment]
Resolved by #367
