### ISSUE TITLE
Add promise support for cancel/update

### ISSUE THREAD

**Issue by creative-eye** [angular-ui/ui-sortable#369]
Some lists might be updated asynchronously or might require AJAX calls that in case of fails would require reverting the last drag and drop. In this case the most reasonable answer would be support for asynchronous canceling of last action. 
What do you think?

**Comment by thgreasi** [comment]
Do you have a sample API in mind to propose?
In case you have to save on every drop then  you could:
1. store the be current state of your model (keep a sallow copy by doing a
`.slice()`) inside the update callback and then initiate your ajax request
2. If the promise of the http request gets rejected, then just assing the
original state from step 1 to your model.

On Sun, Jun 21, 2015, 18:54 Victor Herman <notifications@github.com> wrote:

> Some lists might be updated asynchronously or might require AJAX calls
> that in case of fails would require reverting the last drag and drop. In
> this case the most reasonable answer would be support for asynchronous
> canceling of last action.
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/369>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by creative-eye** [comment]
This solution surely works, however there is no animation to move the dragged elements back when everything is finished. I was thinking more of a stopAsync method that could consume a promise and return false, that would behave just like when the stop method returns false.

**Comment by thgreasi** [comment]
That would probably require changes to jquery-ui-sortable, since currently
there is no way (that I'm aware of) to delay the revert action after the
stop callback.

If the jquery-ui team adds support for a promise based revert API, then we
could surely wrap around it. Currently I can't think a better way to solve
this in our side.

**Comment by thgreasi** [comment]
I have added a [Promised Reverting](http://codepen.io/thgreasi/pen/MwQqdg) example to README.
You might find it useful.

**Comment by creative-eye** [comment]
Thank you. It can be closed.
