### ISSUE TITLE
How do I update an attribute in a model in a ui-sortable list?

### ISSUE THREAD

**Issue by chrismanderson** [angular-ui/ui-sortable#370]
New to ui-sortable and angular, so apologies if this is a dumb question.

Say I have an array of models with a `id`, `name`, `route-order` attribute. I want the `route-order` field to reflect the current order of the index in my ui sortable list. So, if I move something to index 3, all of the route-order fields of all of the items in the array should update to their corresponding index. That way, when I post the changes to my API, everything is updated properly.

Is the way I should accomplish this by looping through the items in `ui.item.sortable.sourceModel` and updating the attribute in there? That seems wrong to me, so wondering if there is a better solution.

Thanks!

**Comment by thgreasi** [comment]
If the priority of your list is stored in an attribute of the model items,
then iterating over the list and updating that property is the only way.
This should be done inside the `stop` callback. This technique is also
applies to the ordering examples found in README.

On the other hand, depending on your API, you could just send an ordered
array with the ids of the items to the backend. Then their ordering could
be inferred from the position of each item in the array.

On Mon, Jun 22, 2015, 18:08 Chris Anderson <notifications@github.com> wrote:

> New to ui-sortable and angular, so apologies if this is a dumb question.
>
> Say I have an array of models with a id, name, route-order attribute. I
> want the route-order field to reflect the current order of the index in
> my ui sortable list. So, if I move something to index 3, all of the
> route-order fields of all of the items in the array should update to their
> corresponding index. That way, when I post the changes to my API,
> everything is updated properly.
>
> Is the way I should accomplish this by looping through the items in
> ui.item.sortable.sourceModel and updating the attribute in there? That
> seems wrong to me, so wondering if there is a better solution.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/370>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
