### ISSUE TITLE
Adding a sort confirmation box

### ISSUE THREAD

**Issue by greenleafmedia** [angular-ui/ui-sortable#375]
I'm trying to add a confirmation box to my sorting table to avoid sloppy clicking.  When a user sorts and item a bootstrap modal opens up and asks if they're sure.  If they say "OK" the sort stays.  If they cancel the sort reverts.

The problem I'm running into is that when I use the `update` method and fire the modal, the code continues to execute and I can't call `ui.item.sortable.cancel()` because it's undefined by the time there's a user click.  Here's my code:
```javascript
var SortController = function (vm, $modal) {
vm.sortableOptions = {
    placeholder: 'ui-state-highlight',
    containment: 'parent',
    cursor: 'move',
    handle: '.dragger',
    tolerance: 'pointer',
    start: function (e,ui) {
        ui.placeholder.height(ui.item.height());
    },
    update: function (e, ui) {
        var modalInstance = $modal.open({
            templateUrl: 'confirmSort.html',
            controller: 'ModalInstanceCtrl',
            size: 'sm',
            resolve: {
                objText: function() {
                    return vm.objText;
                }
            }
        });

        modalInstance.result.then(function () {
            //sort confirmed
        }, function () {
            //revert sort
            ui.item.sortable.cancel();
        });
    }
};
};
```

Thanks for any help.

**Comment by thgreasi** [comment]
I have added a [Promised Reverting](http://codepen.io/thgreasi/pen/MwQqdg) example to README.
You might find it useful.
