### ISSUE TITLE
When changing locked items with ng-class, update is disabled but not drag

### ISSUE THREAD

**Issue by acavestro** [angular-ui/ui-sortable#379]
Hi guys,
I need to enable/disable drag dinamically, so I've taken [your code]( http://codepen.io/thgreasi/pen/GgdeEO) and added a checkbox used as condition in items' ng-class.

Here is my version: http://codepen.io/acavestro/pen/oXmvvo

As you can see, the checkbox prevents the update but it doesn't disable drag.
It it possible?

Thanks
Antonio

**Comment by thgreasi** [comment]
You can use the [cancel option](http://api.jqueryui.com/sortable/#option-cancel).
Here is an [example pen demonstrating cancel](http://codepen.io/anon/pen/rVPxMX).
