### ISSUE TITLE
No droptarget value in ui.item.sortable.droptarget

### ISSUE THREAD

**Issue by mladenko** [angular-ui/ui-sortable#380]
I cant get value of ui.item.sortable.droptarget. When i console.log(ui.item.sortable.droptarget) i get 'undefined' and also when i look in DOM there is droptarget in ui.item.sortable.

**Comment by thgreasi** [comment]
Can you fork one of the example codepen's found in README to demonstrate how your code looks like?

**Comment by mladenko** [comment]
Its ok, I have found it! It was in ui.item.sortable.droptarget.attr("data-ul-id").

**Comment by thgreasi** [comment]
Glad that it wokred for your use case :+1:
As a side note, you might want to try using `ui.item.sortable.droptarget.data("ul-id")` instead of `attr()` to access `data-*` properties.
