### ISSUE TITLE
Touch events are not currently supported

### ISSUE THREAD

**Issue by mattisdada** [angular-ui/ui-sortable#381]
It would be great to see this plugin work with touch events as well as mouse for mobile / tablet use

**Comment by thgreasi** [comment]
Duplicate of: #201 #242 #260 #249
All you need to do, is to include [jQuery UI Touch Punch](http://touchpunch.furf.com/) to your pages.

**Comment by thgreasi** [comment]
Since no one uses the github issues search for this,   it would be great to just add a mention in README.

PRs welcome.
