### ISSUE TITLE
Exception when combining jqueryui draggable with ui-sortable

### ISSUE THREAD

**Issue by mr-unicoder** [angular-ui/ui-sortable#383]
I'm combining ui-sortable with jqueryui draggable widget,
the basic concept is that i have two lists one of them is sortable and the other list isn't but its items are draggable with connectToSortable option linked to the first list.
When i drag an item from the unsortable list and drop it on the sortable one, console logs this error:
Uncaught TypeError: Cannot read property 'length' of undefined (sortable.js line 52)

**Comment by thgreasi** [comment]
Any chance you can share some code?
Did you base your code on the example found in README? Did you just add a vanilla jquery-ui widget? Did you use an other directive for the draggable list?

**Comment by mr-unicoder** [comment]
I managed to solve it by converting the two lists to sortable then cancel sorting on the first list in stop event as explained in your sample (Draggable-Sortable like interaction)
It's working fine now, thanks for your great work ☺

**Comment by thgreasi** [comment]
Congrats :+1:
I'm glad it worked for your use case.
