### ISSUE TITLE
Drag & drop changes existing scopes 

### ISSUE THREAD

**Issue by renehamburger** [angular-ui/ui-sortable#384]
You're probably aware of this but it's not intuitive and should probably be mentioned in your docs:

When an element is dropped at the beginning or in the middle of an existing list, it is not created with a new scope but rather takes over the scope of the element already in that list. All following elements will be moved down and take over the scope of their successor and a new scope will be created for the last element in the list.

This is  problematic for any async callbacks which rely on the scope in the closure remaining the same, e.g. `scope.$watch('a', function() {console.log(scope.b); }`.

You can see this behaviour here: http://codepen.io/leanix/pen/MayjRP.

In the case of rearranging items within a list, everything is as expected: DOM elements are moved together with their scopes.

**Comment by thgreasi** [comment]
That's probably because of the `track by $index` in the `ng-repeat`.
Changing the implementation to use a unique `ID` field gave me different results:
http://codepen.io/thgreasi/pen/vNGggz

**Comment by thgreasi** [comment]
Any feedback on this?

**Comment by renehamburger** [comment]
Yes, great, that does the trick. Thanks!
