### ISSUE TITLE
Mobile browser support?

### ISSUE THREAD

**Issue by hitchcockwill** [angular-ui/ui-sortable#385]
I'm testing this on mobile Safari and Chrome and can't seem to get any of the examples to drag. Is there any mobile browser support for this plugin? It's possible that this is an issue with jQuery Sortable rather than this particular plugin.

**Comment by thgreasi** [comment]
As recommended that other issues, you can use [jquery touch punch](http://touchpunch.furf.com/).
I should probably create a pen example for this As well.
Please report if you have any trouble with it.

**Comment by hitchcockwill** [comment]
Thanks, I'll check that out.

**Comment by thgreasi** [comment]
Just added a touch enabled example in README. Hope this helps.
