### ISSUE TITLE
Accessing other methods from the controller within the "stop" handler

### ISSUE THREAD

**Issue by finalcut** [angular-ui/ui-sortable#388]
I dont want to load up my $scope with a bunch of stuff so perhaps this directive won't work for my needs - or maybe I'm missing something.

What I'd like to do is, from within my controller do something like this:

```js
class ListController{
  constructor($scope, listService){
    this.listManager = new ListManager(listService);
    this.sortableOptions = {
       stop: this.moveItem
    };
  }
  moveItem(event, ui){
    ...
    return this.listManager.saveOrderChange(ui.item.sortable.sourceModel);
    ...
  }
}
```
However, this once I'm in the `this.moveItem` method `this` is no longer the controller but the `ul`; I've lost complete track of the scope of the method.  Is there a way to get it that I don't know?

**Comment by thgreasi** [comment]
Ofcourse this is set to the ul, since stop is a callback. That was always the problem with callbacks in JavaScript. The trick was always to set `var that = this;` in a place where this has the appropriate reference and then, inside your stop callback use (the moveItem function) use that. If you give me a code pen example I cab fix it did you.

**Comment by finalcut** [comment]
I'll work on translating my code into a pen and I'll post it here soon.  Thanks for the response

**Comment by finalcut** [comment]
I've figured it out.. by using angular.element(this)
```js
  moveItem(event, ui){
    ...
    let ctrl =  angular.element(this).scope().ctrl;
    return ctrl.listManager.saveOrderChange(ui.item.sortable.sourceModel);
    ...
  }
```

Here is a codepen that illustrates it.  As you can see I'm using ES6 with babel.  I basically just modified your "simple" example. I had forgotten about the angular.element() method but a co-worker reminded me.

http://codepen.io/anon/pen/QjppKY

**Comment by thgreasi** [comment]
Nononononono, don't do it like this. Using angular.element().scope() is a workaround and will not work if you turn angular's debugInfo off.
Stay inside the language and [use `this.itemMoved.bind(this)`](http://codepen.io/thgreasi/pen/jbBBvN) to force the `this` value inside the callback.

**Comment by finalcut** [comment]
oh, okay. thanks.  That is a much better idea.

**Comment by thgreasi** [comment]
Or you could just not make `itemMoved` a property...
It could be just a function refering to `that`.
Or, if you like it as a method, just [write a callback that would call your method](http://codepen.io/thgreasi/pen/JYWWmJ).

**Comment by thgreasi** [comment]
`bind` is more fancy than `apply` I think :smile:

**Comment by finalcut** [comment]
I definitely like the elegance of the .bind()  A LOT better than the this/that way.

I appreciate your response and multiple options presented.  Much appreciated!

**Comment by thgreasi** [comment]
Have a nice weekend :)

On Fri, Oct 2, 2015 at 9:16 PM Bill Rawlinson <notifications@github.com>
wrote:

> I definitely like the elegance of the .bind() A LOT better than the
> this/that way.
>
> I appreciate your response and multiple options presented. Much
> appreciated!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/388#issuecomment-145112831>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
