### ISSUE TITLE
Not working with horizontal elements?

### ISSUE THREAD

**Issue by cauburtin** [angular-ui/ui-sortable#391]
It doesn't seem working when I try to drag and drop items between the 2 horizontal lists

http://codepen.io/anon/pen/jbmGXM

**Comment by thgreasi** [comment]
Have you read the comments on the README about sorting horizontal lists
https://github.com/angular-ui/ui-sortable/blob/master/README.md#floating

Try using the ui-floating option or a newer version of jquery-ui.

On Tue, Oct 6, 2015, 17:50 Cyril Auburtin <notifications@github.com> wrote:

> It doesn't seem working when I try to drag and drop items between the 2
> horizontal lists
>
> http://codepen.io/anon/pen/jbmGXM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/391>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Also, in the first horizontal list of your example, you are using list2 for
your model which is different from the one used in the ng-repeat.

On Tue, Oct 6, 2015, 18:43 Thodoris Greasidis <thgreasi@gmail.com> wrote:

> Have you read the comments on the README about sorting horizontal lists
> https://github.com/angular-ui/ui-sortable/blob/master/README.md#floating
>
> Try using the ui-floating option or a newer version of jquery-ui.
>
> On Tue, Oct 6, 2015, 17:50 Cyril Auburtin <notifications@github.com>
> wrote:
>
>> It doesn't seem working when I try to drag and drop items between the 2
>> horizontal lists
>>
>> http://codepen.io/anon/pen/jbmGXM
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/angular-ui/ui-sortable/issues/391>.
>>
> --
> *Thodoris Greasidis*
> Computer, Networking &
> Communications Engineer
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by cauburtin** [comment]
Thanks, yes I saw that too 

http://codepen.io/anon/pen/jbmGXM

now the only little issue (with ui-floating or not, it doesn't change much) is that it's a bit hard to insert element at the beginning of horizontal containers

**Comment by thgreasi** [comment]
If that's your only problem, then it is a jquery-ui related issue that you are facing. Should we close this issue?

**Comment by cauburtin** [comment]
yes, thanks
