### ISSUE TITLE
Preventing an item to sort.

### ISSUE THREAD

**Issue by CrackerakiUA** [angular-ui/ui-sortable#394]
For example i have 1 2 3 (items) and i have locked item 2, how can i tell to sortable to not touch that item, it must be on place 2. when i move 3 to 1, it should be 3 2 1 and not 3 1 2.

**Comment by thgreasi** [comment]
I think that this is a duplicate of #274, can you confirm that?
Otherwise, just declare a `stop` callback and manipulate your `ng-model` to ensure that after the sorting, item 2 is in the right position.

**Comment by CrackerakiUA** [comment]
http://codepen.io/thgreasi/pen/xDfyk in your codepen, grey objects is not allowed to sort, but they lost they position after others item get sorted.

**Comment by thgreasi** [comment]
I understood your use case from the beginning.
I just asked:
> I think that this is a duplicate of #274, can you confirm that?

and also suggested that you could fix that using the `stop` callback option to change your model as you like.

**Comment by CrackerakiUA** [comment]
What i can do with stop, is to fix result, that can work yes. But awesome would be to freeze that item in the place, not even move.

**Comment by CrackerakiUA** [comment]
Yes, duplicated, i readed it second time :)
