### ISSUE TITLE
debugInfo issue is back?

### ISSUE THREAD

**Issue by chino23** [angular-ui/ui-sortable#395]
Hi,

using this for a bit and never had problems.

Now I'm on angular 1.4.7 and just realized, it doesn't work anymore with debuginfo disabled.

Anyone have the same issue? Maybe it's a new angular thing? Cause it used to work fine for a while. I'm on the latest release.

**Comment by chino23** [comment]
Some more info:

This is a line inside the stop: function I use, and it works flawlessly with debuginfo enabled:

    stop: function (e, ui) {
        updateData(ui.item.scope().project.id)
    }

Now when I disable it, it says 
    
    Cannot read property 'project' of undefined

So the ui.item.scope() isn't working. I use this function to access the project ID of the item I'm dragging. 

Anyone got a fix for that, as it seems the only thing not working with the debugInfo disabled?

**Comment by thgreasi** [comment]
That's actually what disabled debug info means, it does not add all these extras on the elements out the page. So, pageelement.scope() isn't going to work with d disabled debug info.
Just use v`ui.item.sortable.model` instead, as shown in the API page and in some examples.

**Comment by chino23** [comment]
Thanks a lot for the quick reply! It works flawlessly.

I guess my code was still stuck in the old ways (from last year, actually) :)

Happy to see this project still active. Love it!

**Comment by thgreasi** [comment]
Glad it works for you. Have a great ng-dev-day!

**Comment by chino23** [comment]
Thanks, you too!
