### ISSUE TITLE
ui.item.index() returns -1 when using connectWith

### ISSUE THREAD

**Issue by jasonpolites** [angular-ui/ui-sortable#396]
In the ```stop()``` event callback of the sortable options one can inspect the final index of the dropped item by reading ```ui.item.index()```

For example:
```javascript
{
    stop: function (event, ui) {
        console.log(ui.item.index());
    }
}
```
However when using ui-sortable, the index returned when dragging *between* lists is **-1**

"vanilla" jquery-ui sortable appears to work correctly.

You can see the behavior with Angular (fail case) here:

http://jsfiddle.net/jz0498bb/

And the vanilla jquery version (success case) here:

http://jsfiddle.net/82e0c3b0/

In each case, drag an item from one list to the other (e.g. left to right) and see the input field display the final index of the dragged item.  When dragging between lists in the angular version, you'll see **-1** returned.

**Comment by thgreasi** [comment]
Hi there. That's probably because in ui-sortable we are canceling the
original sorting after the update even (with .cancel()) and then try to
apply it through changing the ng-model of the ng-repeat. You can try using
the [ui.iyem.sortable.dropindex](
https://github.com/angular-ui/ui-sortable/blob/master/API.md#dropindex)
that we fill for this reason.

On Tue, Oct 27, 2015, 09:57 Jason <notifications@github.com> wrote:

> In the stop() event callback of the sortable options one can inspect the
> final index of the dropped item by reading ui.item.index()
>
> For example:
>
> {
>     stop: function (event, ui) {
>         console.log(ui.item.index());
>     }
> }
>
> However when using ui-sortable, the index returned when dragging between
> lists is *-1*
>
> *vanilla* jquery-ui sortable appears to work correctly.
>
> You can see the behavior with Angular (fail case) here:
>
> http://jsfiddle.net/jz0498bb/
>
> And the vanilla jquery version (success case) here:
>
> http://jsfiddle.net/82e0c3b0/
>
> In each case, drag an item from one list to the other (e.g. left to right)
> and see the input field display the final index of the dragged item. When
> dragging between lists in the angular version, you'll see *-1* returned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/396>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Feel free to reopen if that doesn't fix your problem.

**Comment by thgreasi** [comment]
http://jsfiddle.net/jz0498bb/2/

**Comment by jasonpolites** [comment]
Hey sorry for the late reply.  Thanks for the solution :)

**Comment by thgreasi** [comment]
I'm glad it worked for you 😀
