### ISSUE TITLE
How to add ui-sortable attribute conditionally?

### ISSUE THREAD

**Issue by im1dermike** [angular-ui/ui-sortable#397]
It does not appear this directive has the ability to be added conditionally.  If you attempted to implement this functionality like it's implemented for `required` and `ng-required`...

This:  `<ul ng-model="items" ui-sortable>`

Would look like this:  `<ul ng-model="items" ui-sortable="isSortable">`

Unfortunately, `ui-sortable` was designed to be able to take an optional `options` value.  I believe this is also what makes the built-in `ngAttr` directive not work.  https://docs.angularjs.org/guide/directive#text-and-attribute-bindings

Any way to get around this?

**Comment by thgreasi** [comment]
There actually exists a [disabled optio]()

**Comment by thgreasi** [comment]
A [disabled option](https://api.jqueryui.com/sortable/#option-disabled) actuate exists and should be a perfect match for your use case.
Does it?
