### ISSUE TITLE
Binding between cloned element and source

### ISSUE THREAD

**Issue by NHenzen** [angular-ui/ui-sortable#399]
Hi,
I have created the cloning example if i edit the cloned element the source model changes as well

[link to codepen!] (http://codepen.io/nick-henzen/pen/jbpYNZ) -> drag an element to the list on the right than click on it to change the model.

is there anyway to remove this binding or prevent this binding form being created ?

Thanks

**Comment by thgreasi** [comment]
Use [angular.copy](http://devdocs.io/angular/ng/function/angular.copy) to actually create a deep clone of the model of the dragged item.
Like [this for example](http://codepen.io/thgreasi/pen/LpBrzz).

**Comment by thgreasi** [comment]
Is this enough for your use case?

**Comment by NHenzen** [comment]
Thanks, This fits my use case exactly.
