### ISSUE TITLE
Sorting horizontally sometimes updates the wrong items 

### ISSUE THREAD

**Issue by joshbedo** [angular-ui/ui-sortable#402]
I just setup ui-sortable and i'm experiencing some funky issues with horizontal sorting. I was wondering if bugs still exist around horizontal sorting? I tried floating:true and axis: x... however they didn't do much if anything. 

Thanks!

**Comment by thgreasi** [comment]
Does the horizontal list example from README work for you? Any chance you
can share an example with the use case that troubles you?

On Thu, Nov 5, 2015, 02:01 Josh Bedo <notifications@github.com> wrote:

> I just setup ui-sortable and i'm experiencing some funky issues with
> horizontal sorting. I was wondering if bugs still exist around horizontal
> sorting? I tried floating:true and axis: x... however they didn't do much
> if anything.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/402>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by joshbedo** [comment]
The Horizontal List example links to a Vertical List example. Yeah i'll put something together today.

**Comment by joshbedo** [comment]
@thgreasi here is a video of what i'm seeing - http://screencast.com/t/Rjiilubss

Basically i can't sort the order because other non-selected items that are hovered jump to a new location... either that or too many items are in the drop zone.

**Comment by joshbedo** [comment]
With bootstrap its a little less jumpy but the resorted order makes no sense - http://screencast.com/t/t4Bxjzg9M

**Comment by joshbedo** [comment]
So i ended up fixing the issue. I realized i had `orderBy` in my view which was causing issues.. after i moved that to the controller it worked fine. The other issue was that i called update on the update method but that should be done on the stop method. So changing those two things solved the problems.

**Comment by thgreasi** [comment]
I think that there is a button that toggles the layout to horizontal, isn't
it?
Anyway I'm glad you found your way through the docs / trial & error...
:+1: for being one of those who apply their filters in their controllers!

On Thu, Nov 5, 2015, 18:20 Josh Bedo <notifications@github.com> wrote:

> Closed #402 <https://github.com/angular-ui/ui-sortable/issues/402>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/402#event-455907496>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
