### ISSUE TITLE
it duplicates dragging element in DOM

### ISSUE THREAD

**Issue by i10111pn** [angular-ui/ui-sortable#404]
Hi,
could you please check if it a bug: http://codepen.io/anon/pen/ZbMzgL

Use case: I need transform drag list using ng-class.

Steps to reproduce:
  1. Start dragging red list in left column.
  2. Drop it into left column.

ui-sortable create duplicate of drag list:

![ui-sortable_bug](https://cloud.githubusercontent.com/assets/11459051/10968985/fe70dae6-83cd-11e5-9676-b3a8b450cd4f.jpg)

Note that we don't have ng-class for right column's drag list,
as result - no bug in right column.

**Comment by thgreasi** [comment]
I would suggest you not to after the classes of the dragged element during
sorting. If you need to make the dragged element appear differently, then
you should use the "helper" option. I think that there is as example for
that in README that creates a clone of the dragged element for presentation
reasons.

On Thu, Nov 5, 2015, 15:06 Yevgen Motrych <notifications@github.com> wrote:

> Hi,
> could you please check if it a bug: http://codepen.io/anon/pen/ZbMzgL
>
> Use case: I need transform drag list using ng-class.
>
> Steps to reproduce:
>
>    1. Start dragging red list in left column.
>    2. Drop it into left column.
>
> ui-sortable create duplicate of drag list:
>
> [image: ui-sortable_bug]
> <https://cloud.githubusercontent.com/assets/11459051/10968985/fe70dae6-83cd-11e5-9676-b3a8b450cd4f.jpg>
>
> Note that we don't have ng-class for right column's drag list,
> as result - no bug in right column.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/404>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by i10111pn** [comment]
It can be solved by moving `ng-class` from drag list to container of drag list.
As result we don't changing drag list in DOM while grading.
Also we need to add proper css.

http://codepen.io/anon/pen/GpXVqo

Thanks for answer.

**Comment by thgreasi** [comment]
Glad it worked for you!
