### ISSUE TITLE
ui-sortable problem when using ui-rangeSlider

### ISSUE THREAD

**Issue by itskashi** [angular-ui/ui-sortable#406]
Hi -
I am using ui-sortable with ui-rangeSlider. 
I have a list  of item to sort in a div. 
and I have the slider  on the same page. 
Initially the sort and drag and drop works fine. But one you play with slider the ui-sortable stops working and I can not drag drop sort the lists any more. 

Looks like there is something connected to Model change but I tested this with a very simple model and still it does not work. Can you please look into the issue. 

Is there anything that I must do to refresh the ui-sortable during or after the slider  events are called.

**Comment by thgreasi** [comment]
Hi there, can you fork one of the examples found in README and provide me an example to test on?

**Comment by thgreasi** [comment]
Any feedback on this?

On Thu, Nov 12, 2015, 10:28 itskashi <notifications@github.com> wrote:

> Hi -
> I am using ui-sortable with ui-rangeSlider.
> I have a list of item to sort in a div.
> and I have the slider on the same page.
> Initially the sort and drag and drop works fine. But one you play with
> slider the ui-sortable stops working and I can not drag drop sort the lists
> any more.
>
> Looks like there is something connected to Model change but I tested this
> with a very simple model and still it does not work. Can you please look
> into the issue.
>
> Is there anything that I must do to refresh the ui-sortable during or
> after the slider events are called.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/406>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Any further feedback on this?
Do you have difficulties creating an example pen? Anything I could possibly
help you with?

On Mon, Nov 16, 2015, 09:30 Thodoris Greasidis <thgreasi@gmail.com> wrote:

> Any feedback on this?
>
> On Thu, Nov 12, 2015, 10:28 itskashi <notifications@github.com> wrote:
>
>> Hi -
>> I am using ui-sortable with ui-rangeSlider.
>> I have a list of item to sort in a div.
>> and I have the slider on the same page.
>> Initially the sort and drag and drop works fine. But one you play with
>> slider the ui-sortable stops working and I can not drag drop sort the lists
>> any more.
>>
>> Looks like there is something connected to Model change but I tested this
>> with a very simple model and still it does not work. Can you please look
>> into the issue.
>>
>> Is there anything that I must do to refresh the ui-sortable during or
>> after the slider events are called.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/angular-ui/ui-sortable/issues/406>.
>>
> --
> *Thodoris Greasidis*
> Computer, Networking &
> Communications Engineer
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by ddxy** [comment]
Hi, i have the same problem. Using ui-slider breaks sortable-functionality. I can send you an example if you need one.

**Comment by ddxy** [comment]
Here is the link:
http://codepen.io/anon/pen/wMwNOQ

After using the range-slider, i can sort the list one time and then it stopped working :(

**Comment by thgreasi** [comment]
Thanks for the example pen
That's very interesting....
We might be messing with each other's even handling....
I will investigate, but please post this issue to the repository of RangeSliden as well.

**Comment by ddxy** [comment]
Thanks for the fast answer! I posted it on his repo, but he seems inactive for quiet a while.
If you find a fix, i would be happy if you can keep me up2date :-), since i need both plugins for my thesis :-)

**Comment by thgreasi** [comment]
Related to danielcrisp/angular-rangeslider#92.
Have you considered trying an alternative directive, like: [angular-ui/ui-slider](https://github.com/angular-ui/ui-slider) ?

**Comment by ddxy** [comment]
looks promising, i will try it out. Thanks!!

**Comment by thgreasi** [comment]
Any feedback on this? Have you managed to make it work? Should this issue
be closed?


-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by ddxy** [comment]
It works perfect with ui-slider, thanks!
