### ISSUE TITLE
Access ng-model in update:callback

### ISSUE THREAD

**Issue by sinjaz** [angular-ui/ui-sortable#408]
I have several < ul >'s dynamically generated on the same level of my HTML and they're all using the same sortableOptions. Is there a clean way to pass/access the ng-model of the < ul > that was updated in the callback method?

`item.sortable.model` is undefined.

**Comment by thgreasi** [comment]
[Here an example pen](http://codepen.io/thgreasi/pen/epXWqP).
Feel free to re-open if something troubles you.
