### ISSUE TITLE
Class customization

### ISSUE THREAD

**Issue by Deklin** [angular-ui/ui-sortable#409]
Is there a way in this scenario

ul ui-sortable ...
li ng-repeat.../li
/ul

to add a class on the ul where ui-sortable is when a drag/sort has been started and remove it when it stops? specifically on the UL and not the LI

**Comment by thgreasi** [comment]
You should able to achieve this by using ng-class utilizing the start & stop callbacks to set the value of a scope variable.

**Comment by thgreasi** [comment]
[Here is an example pen with my suggestion](http://codepen.io/thgreasi/pen/dYrWry).
Keep in mind that you might have to use $apply yourself. We are not calling $apply internally, in order to avoid unnecessary digest loops while dragging, that could possibly break the sorting.
