### ISSUE TITLE
Support more elements inside the directive, not just ngRepeat

### ISSUE THREAD

**Issue by romario333** [angular-ui/ui-sortable#41]
*Previous Title: "Empty item is inserted to array after reorder if there are non-sortable siblings"*

If you setup `ui-sortable` to sort only some elements in the container (e.g. by configuring sortable with `items: '> .sortable'`) and keep in sync with model via `ng-model`, there is a risk that new empty items will be inserted into the array.

Have a look at demo [here](http://plnkr.co/edit/jig1IizG5a9L9poLTVre?p=preview). Grab the second item and put it before the first. The new empty item is created.

**Comment by thgreasi** [comment]
Fixed in v0.14 by #344
