### ISSUE TITLE
Droppable area not recognized on scroll?

### ISSUE THREAD

**Issue by CLGitDev** [angular-ui/ui-sortable#411]
I am experiencing a problem in which the droppable area is no longer detected on scroll.

Here is my project setting:
1. A parent div container with auto overflow;
2. A long list of arrays on the left, which the corresponding items will be shown on hover;
3. A list of items on the right

A codepen project is set up for better illustration at http://codepen.io/anon/pen/ojrNxm

The general use case is, user will drag an item, hover on the array they want the item to be moved to, and drop the item there. It works well when the the array hovered is nearby, say moving **Item 1** from **Array 0** to **Array 8** works. However as long as scroll is involved, say moving **Item 1** to **Array 20**, the item cannot be dropped.

I have an impression that it is something to do with the positioning of the item on scroll; however I am unable to turn my head around on this. Any help will be greatly appreciated!

**Comment by CLGitDev** [comment]
I've simplified the codepen project to make the scenario more easy to understand.
http://codepen.io/anon/pen/mVJMaZ

**Project Setting**
1. Two lists within the same container, with overflow-y set to auto.
2. On drag, item will be appended to the container.

**Test Cases**
1. Dragging item 8 from left list to right list << works fine
2. Dragging item 15 from left list to right list << not working; unless the item is dragged above the container until the scroll offset is compensated

**Impression**
Looks like I'll need trigger a refreshPositions method (if it helps) if scroll is involved. But I'm not sure where should this method be triggered.

Thanks in advance for your help!

**Comment by thgreasi** [comment]
@CLGitDev Sorry it took me so long to respond on this.
The new codepen example and the highly detailed description helped a lot :+1: 
Even though this is a jquery-ui issue, I think that I found [a working solution](http://codepen.io/thgreasi/pen/YwXrLy).
Does this suffice for your use case?
Consider re-opening this issue if something is wrong.

**Comment by CLGitDev** [comment]
@thgreasi No worries mate, it's great to hear back from you, you always bring good news to me.

I've quickly plugged your solution to my own project and it seems to be working fine. I'll do more thorough testing and revert in case of any issues.

Thanks once again for your help!

**Comment by thgreasi** [comment]
I'm glad it worked for you :smile:
