### ISSUE TITLE
Snap to element or grid option?

### ISSUE THREAD

**Issue by cquillen2003** [angular-ui/ui-sortable#412]
Is the "Snap to element or grid" functionality from jQuery UI Draggable available in ui-sortable?

I'm trying to build a sortable list of items that can be dragged and dropped onto specific slots on a calendar-like table.  Is this possible with ui-sortable?

Thank you!

**Comment by thgreasi** [comment]
[It should work](http://codepen.io/anon/pen/obNqGp), since we are not interfering with the jQuery-ui options, just pass them around.
But you might end up creating multiple [dropzones](http://codepen.io/thgreasi/pen/LVXWeO) for each slot of a month.

**Comment by thgreasi** [comment]
BTW Have a great weekend!
