### ISSUE TITLE
angular.copy() the sorted $scope variable returns wrong elements

### ISSUE THREAD

**Issue by sszdh** [angular-ui/ui-sortable#413]
Hi,

This is [pen](http://codepen.io/sszdh/pen/xZxjPy?editors=101) for reproduce issue. (see browser's `console` to compare two list)
With trying a couple of sorting and comparing you can see that the `copy` version always has old value of `original` instead of it's current value!   

Actually I try to send updated model array with `Restangular` in `update` event, but in each request the provided json list is wrong! It seems `Restangular` uses `angular.copy` or `angular.toJson` to send passed items.

Thanks.

**Comment by sszdh** [comment]
My bad,

I think, I should use `stop` event for this. As the doc mentioned:

> update is the appropriate place to cancel a sorting, __since it occurs before any model/scope changes__ but after the DOM position has been updated. **So ui.item.scope and the directive's ng-model, are equal to the scope before the drag start**.

Thanks.

**Comment by thgreasi** [comment]
I'm glad you found your way around the docs :+1:.
I you have any suggestions for improving the docs, feel free to discuss it here or in a new issue/PR.
