### ISSUE TITLE
Question: What event to use to update order attribute on dragging and dropping in nested connected list

### ISSUE THREAD

**Issue by preethi29** [angular-ui/ui-sortable#415]
I have a nested connected list and I want to update a attribute 'order' (order index) in each element on sorting the elements. On dragging an element from child list to parent list, I want to update the order attribute for elements in both parent and child list. 
Lets say, list structure is like below:
```  list1
     - child 1 { order: 1}
     - child 2  {order: 2}
     - child 3 ( also a list) {order: 3}
           - child 3.1 {order: 1}
           - child 3.2 {order: 2}
```
Now on dragging the element child 3.2 to list1 as the 1st child, I want the 'order' attribute of all the elements to get updated accordingly.
I have tried using 'remove' and 'receive' events - it updates the order attribute of all the elements in both the list except the element being moved since 
- 'remove' event is triggered on the 'child 3' once the element is removed 
- 'receive' event is triggered on the 'list 1' before the element is added.
- 'stop' event is triggered only on the list from which the element is removed. So could not update the destination list

Which event would solve this problem. Please help.

**Comment by thgreasi** [comment]
I wound suggest you to use the stop callback, which is fired right after
the html and the models have been updated. There you can use the ui
argument to access the models of both lists that participated to the
sorting and manipulate the order attribute of their items.
Have you seen the ordering examples in the README?

-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by preethi29** [comment]
Can I access both the lists in stop event? Because it is a nested connected list implemented by calling directive(with isolated scope) recursively. I figured out that stop event is always trigged on the source list.

**Comment by preethi29** [comment]
Cool, I got what you were suggesting. Was able to access both the lists using sourceModel and dropTargetModel. That helped.

**Comment by thgreasi** [comment]
I'm glad that it worked for you!
Should we close this now?
