### ISSUE TITLE
Question: Can we integrate this in Angular-DataTable?

### ISSUE THREAD

**Issue by dashawk** [angular-ui/ui-sortable#417]
Hey guys,

I am currently using [angular-datatables](https://github.com/l-lin/angular-datatables) for my table needs. I wanted my table to have row reordering.

In a normal table, the sortable just works fine. But when using [angular-datatables](https://github.com/l-lin/angular-datatables), it will not update the text in the row, but the actual source model is already updated.

Here is my HTML markup:
```html
<table datatable dt-instance="vm.tableInstance">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
		</tr>
	</thead>
	<tbody class="sortable-container" ui-sortable="sortableOptions" ng-model="itemList">
		<tr ng-repeat="item in itemList" class="item">
			<td>{{ item.id }}</td>
			<td>{{ item.name }}</td>
		</tr>
	</tbody>
</table>
```
My angular controller:
```js
function tableController($scope) {
	$scope.sortableOptions = {
		connectWith: '.sortable-container',
        items: '.item',
		helper: function (e, ui) {
		    ui.children().each(function() {
		        $(this).width($(this).width());
		    });
		    return ui;
		},
		stop: function (event, ui) {
			// My stuff here
		}
	};
}
```

I don't know why its not working with the angular-datatables directives.

**Comment by thgreasi** [comment]
Hi there and thanks for reporting this issue.
Can you please provide a codepen example with the use case that isn't
working?  Since I'm not familiar with the datatables directive, it would be
very helpful for identifying what the issue is.

-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by dashawk** [comment]
Hi, thanks for the reply. I tried to create a jsfiddle for the problem but I keep on getting an error: `element.sortable is not a function` when trying to add `ui-sortable` in the `<tbody>`.

Here is the [jsfiddle](http://jsfiddle.net/yx5t5s6j/).

**Comment by thgreasi** [comment]
You are missing a reference to jquery-ui.

**Comment by thgreasi** [comment]
[This fiddle](http://jsfiddle.net/yx5t5s6j/2/) seems to be working now. Can you demonstrate your use case?

**Comment by dashawk** [comment]
HI,

Thanks for the quick responses.

I updated the [fiddle](http://jsfiddle.net/yx5t5s6j/6/) to use the angular-datatables directive and it seems to work fine. But the datatable is not working.

In my fiddle, the show filter is not working but the sorting is working just fine.

I can't really explain it in words since my codes in fiddle is just the same as in my project so i will just show you a video on how my project behaves on ui-sortable with angular-datatables.

Here is the [video demo](https://drive.google.com/file/d/0B8EqmxaLO06JR3BGNDlBRVBLb28/view?usp=sharing) in the issue.

Thanks.

**Comment by thgreasi** [comment]
When using the provided fiddle url, I'm getting an
`Error 404
We're truly sorry, but there is no such page.`.
Any chance this is a private fiddle or something?

On Tue, Dec 15, 2015, 04:40 Jason Panugaling <notifications@github.com>
wrote:

> HI,
>
> Thanks for the quick responses.
>
> I updated the fiddle <http://jsfiddle.net/yx5t5s6j/6/> to use the
> angular-datatables directive and it seems to work fine. But the datatable
> is not working.
>
> In my fiddle, the show filter is not working but the sorting is working
> just fine.
>
> I can't really explain it in words since my codes in fiddle is just the
> same as in my project so i will just show you a video on how my project
> behaves on ui-sortable with angular-datatables.
>
> Here is the video demo
> <https://drive.google.com/file/d/0B8EqmxaLO06JR3BGNDlBRVBLb28/view?usp=sharing>
> in the issue.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/417#issuecomment-164625868>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
As first attempt to fix the problem, try adding a `track by id` to the
ng-repeat.
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by dashawk** [comment]
Hi,

I tried adding the `track by id` or `track by item.id` but it still cannot track the current row that is being moved.

**Comment by thgreasi** [comment]
I'm glad that It worked for you, even thought I would prefer to track by
something else than the index.
Should this be closed now?

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by dashawk** [comment]
I also prefer to use other identifiers for the `track by` but `$index` is already working so I'll just keep it for now.

Thanks for the help. I think this should be closed now.
