### ISSUE TITLE
[Proposal] Changing row roles (parent/child)

### ISSUE THREAD

**Issue by dashawk** [angular-ui/ui-sortable#418]
Hi @thgreasi,

I am just wondering if we can do this in a table from this [wordpress example](https://googledrive.com/host/0B8EqmxaLO06JZXhCV0lxMFUyNjA) though wordpress is using unordered list `<ul>`

Thanks.

**Comment by thgreasi** [comment]
What you are proposing is a nested structure, not a flat array.
Have you seen the [Tree with dynamic template example](http://codepen.io/thgreasi/pen/uyHFC) in README ?
The only thing yo need to do to achieve the same result is to fine-tune the [jquery-ui-sortable](https://api.jqueryui.com/sortable/) options that will be used.
