### ISSUE TITLE
Question: How to reverse changes in stop state

### ISSUE THREAD

**Issue by sszdh** [angular-ui/ui-sortable#420]
Hi,

I have a `sortable` list with this option attached:

```js
var options = {
    stop: doOrder
}
```

and in controller:

```js
angular
        .module('App')
        .controller('MyController', MyController);

MyController.$inject = ['$scope', 'MyService'];

function MyController($scope, MyService) {
    var vm = this;
    
    vm.items = []
    vm.options = {
        stop: doOrder
    };

    __initialize();
    
    function __initialize() {
        return refresh()
    }

    function doOrder(event, ui) {
        var promise = MyService.orderItmes();

        promise.then(null, function(res){
            ///// I want to reverse changes and reset `vm.items` to original state!
        });
    }

   function refresh() {
       vm.items = MyService.getItems();
       return vm.items;
   }
}
```
I want to reverse changes and reset `vm.items` to original state in case of any server errors!
Using `angular.copy()` in `stop` state, does not help.

So, the question is, how I can access original `ng-model` in `stop` state of list.

P.S. I know that I can make a new request and fetch items from server then refresh it, but I want to do it without any additional requests.

Thank.

**Comment by thgreasi** [comment]
Hi there.
Have you seen the [Promised Reverting canceling example](
http://codepen.io/thgreasi/pen/MwQqdg) that **is available in README**???
This is using a dialog as an example where the result becomes available
asynchronously. The concept is to clone the array before the sort starts
and revert the model when you need to undo the last sorting. This is a
shallow copy of the array using slice() and as a result it is very
performant and memory efficient, since it only requires 4 bytes per item.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
I'm closing this for now. Please feel free to reopen in any case.

**Comment by sszdh** [comment]
@thgreasi Thank you very much. That is what I exactly want.

So this is what I ended up with finally:

```js
angular
        .module('App')
        .controller('MyController', MyController);

MyController.$inject = ['$scope', 'MyService'];

function MyController($scope, MyService) {
    var vm = this;
    var origin = [];

    vm.items = origin;
    vm.options = {
        start: sortStart,
        stop: doOrder
    };

    __initialize();

    function __initialize() {
        return refresh();
    }

    function sortStart(event, ui) {
        origin = vm.items.slice();
    }

    function doOrder(event, ui) {
        var promise = MyService.orderItmes();

        promise.then(null, function(res){
            vm.items = origin;
        });
    }

   function refresh() {
       vm.items = MyService.getItems();
       return vm.items;
   }
}
```
Cheers.
