### ISSUE TITLE
ui.sortable + angularfire / firebase

### ISSUE THREAD

**Issue by mastef** [angular-ui/ui-sortable#421]
I'm having really big issues in making ui.sortable work with angularfire / firebase when working with 2+ drag & drop lists on 2 models.

Technically what I'd like to achieve is working with 2 lists based on the same model with filters ( `status:open`, `status:closed` ), and when I drop an item from list a to list b it would simply change the model's status. Now that doesn't seem plausible at this stage from my research, so let's say we work with 2 models bound to a scope `model.open`, `model.closed`.

#### Issue 1 : The input data must be an array

It's super-easy to work with Firebase objects, as they auto-sync through 3-way-bindings. However currently it seems that ui.sortable requires an array. Arrays come with numeric indexes, which make it really hard to manage when you have multiple users working on the same data set at the same time.

E.g. I move `list1[0]` to `list2`, while somebody else is updating `list1[1]`'s value....

By using an Object I'd be moving `list1["-ABC"]` to `list2`, while the 2nd user would be updating `list1["-DEF"]`. No bigger concurrency issues here except handling a concurrent edit on `list1["-ABC"]` while it was moved to `list2`.

But even that can be handled by keeping them on the same model with a filter instead. Hence Object's keys are better for collaborative working.

Possible solutions :

1. Making ui.sortable work with Objects and doing list movements based on the Object's Key
2. Adding prototype methods to an Object to handle functions such as .splice() - seems messy

#### Issue 2 : Avoiding `splice`, `pop`, `push`, `shift` and `unshift` by using own methods

It's possible to work with Firebase and retrieve the data as an array https://www.firebase.com/docs/web/libraries/angular/guide/synchronized-arrays.html - however any operations that are done with `splice(), pop(), push(), shift(), and unshift()` won't be synced back to the server due to the dangers of numeric indexes and server-side changing data. ( See https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray )

What Firebase suggests is instead using `$add()`, `$remove()`, and `$save()` methods with the array.

Possible solutions :

1. Is it possible to override the `ui.sortable` methods to use the above mentioned ones instead? So instead of using splice, push, etc, that we could define that it uses `$add()`, `$remove()`, and `$save()` instead? That way we'd have no sync problems, and the models update right away online and in the local models, so actually ui.sortable wouldn't have to update the arrays themselves.

2. Another solution that turned out very messy : Backing up the current array snapshot on `beforeStop` and `update`, and then deleting all old items at `stop` and finally re-adding items from the latest state to the firebase array. But this is a tremendously messy and error prone method while testing with one user alone; as basically each user keeps rewriting all data on every change.

Those are the 4 possible solutions. Any ideas? Overall I think a support for objects + keys would be really nice.

**Comment by mastef** [comment]
Related issues : https://github.com/firebase/angularfire/issues/19#issuecomment-31227995, https://github.com/firebase/angularfire/issues/200#issuecomment-39157760 and http://stackoverflow.com/questions/25896957/using-angular-ui-sortable-and-angularfire-is-there-a-way-to-save-the-new-order-t ( this one does the priority assignments on 'stop', doing that it saves the whole array back to firebase. However doesn't handle removing of moved items )

It would be really amazing if ui.sortable and angularfire/firebase could work out of the box!

**Comment by thgreasi** [comment]
You can build on top of that and implement callbacks for the remove and
receive options. I prefer this approach, since splicing an object isn't
going to be a performant solution (I think).
If you can provide me an example codepen, I could give it a try during
holidays.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by mastef** [comment]
Hey @thgreasi, I have created a fix that currently works for me, by changing the sortable.js itself.

Check out the revision 2 of this gist : https://gist.github.com/mastef/0ae8ba7595cafad2c85f/revisions?diff=split

This works with an example code like :

```
	$scope.idea = $firebaseArray(fbutil.ref('todo/Idea').orderByPriority());
	$scope.idea.$loaded().catch(alert);

	$scope.inprogress = $firebaseArray(fbutil.ref('todo/InProgress').orderByPriority());
	$scope.inprogress.$loaded().catch(alert);

	$scope.done = $firebaseArray(fbutil.ref('todo/Done').orderByPriority());
	$scope.done.$loaded().catch(alert);

	$scope.sortableOptions = {
	  connectWith: ".connectList"
	};
```

Which basically moves one item between 2 $firebaseArrays. This specific example itself moves the item only between 2 different paths.

I've seen some of the examples that would allow similar behaviour by using applied filters and changing the moved object at drop ( e.g. just changing a property "status" to "idea", "inprogress", etc ), but haven't implemented that yet. That way it would only update a key/value of the item, instead of moving it between 2 paths which would be even nicer.

Should work nevertheless with that gist version. So I think the question would be - is it possible to override these callbacks without changing the main file?

**Comment by thgreasi** [comment]
:+1: That's great!
Maybe you could implement a firebase-friendly version of splice and monkey
patch on your model. Would that work with firebase?

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by mastef** [comment]
@thgreasi that was my first thought, but I don't believe hacking splice would be the right way to work with firebase. Maybe @katowulf will have more insights on this, I've created a separate issue at https://github.com/firebase/angularfire/issues/687 for this

**Comment by thgreasi** [comment]
It will be nice to hear their opinion and ideas as well.
This should be better solved either in our side with a custom update
function, or in the developer's side where the array and firebase
collection should be kept in sync.
Maybe we can create a suggested integration example or configuration
extended plugin like https://github.com/thgreasi/ui-sortable-multiselection

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Maybe we can create a Proxy object for the firebase collection and override
splice in there!?!?
(So that the original firebase object is kept intact).
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Happy new year btw!
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Hi there. Just saw that firebase/angularfire#687
<https://github.com/firebase/angularfire/issues/687> has been closed.
Should we also close this one after adding an integration example in
README.md ? Would anyone be interested on helping with the codepen example?
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
@mastef Just pushed 4f18c64b50b795dd3b499e40755b9deac538d056 that adds a [firebase sortable integration example in README](http://codepen.io/thgreasi/pen/repEZg?editors=0010), based on the great code example noted in firebase/angularfire#687.
Any feedback would be great. Feel free to re-open in something seems wrong.
