### ISSUE TITLE
how to prevent new item to insert if same item is already present in list?

### ISSUE THREAD

**Issue by Abhivendra** [angular-ui/ui-sortable#422]
example i have div with content 1 to 10 and if i am inserting 4 again , how can i prevent it or show duplicate entry ?

**Comment by thgreasi** [comment]
Check the properties of ui.item.sortable inside the update callback and
cancel the sorting. I think there is already an example or an issue related
with this. So make a search.

On Thu, Jan 7, 2016, 00:20 Abhivendra Singh <notifications@github.com>
wrote:

> example i have div with content 1 to 10 and if i am inserting 4 again ,
> how can i prevent it or show duplicate entry ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/422>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
There is already an example for preventing duplicates in README. Feel free to reopen.
