### ISSUE TITLE
Trouble adding ui-sortable as a dependency of application.

### ISSUE THREAD

**Issue by YonasBerhe** [angular-ui/ui-sortable#423]
Error message

``` Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=swurveys&p1=Error%3…0at%20d%20(http%3A%2F%2Flocalhost%3A8000%2Flib%2Fangular.min.js%3A19%3A385)```

Added library via src file in project 'ui-sortable'. Do I have to do a bower install for it to work?

**Comment by thgreasi** [comment]
The error provided does not actually refer to ui-sortable.
Can you elaborate more on your configuration or even better provide an example codepen/jsfiddle.
Please refer to the (many) codepen examples that are available in README.

**Comment by YonasBerhe** [comment]
Solved
