### ISSUE TITLE
On drag is causing other elements in array to adding some sort of padding top

### ISSUE THREAD

**Issue by YonasBerhe** [angular-ui/ui-sortable#424]
I'm using your library for elements in my header bar / nav bar. I have a list of card that are populated via a ng-repeat. I'm instantiating your library on the ul. 

Code : 
```   
<ul   ui-sortable="{ 'ui-floating': false }" drag-scroll ng-model="cards" class="nav-list nav-scroll">
      <div class="nav-list-item" ng-repeat="card in cards">
        <li class="nav-button nav-elements" ng-click="switchNavTab($index + 1)" >
          <a>
            <p>{{$index + 1}}</p>

           
            <p class="nav-text text-centered" >{{card.type}}</p>
          </a>
        </li>
        <div class="triangle-cards" ng-hide="navTab !== ($index+1)"></div>

          </ul> 

```

Each time I try to drag one of these elements, they all slightly move down. Although I can still change the order of my elements its causing a pretty bad effect.

**Comment by thgreasi** [comment]
I think that's is jquery-ui related. Please search there for a solution.
Moreover I think that having a div as a child of your ul might cause
troubles to you anyway.
Lastly I think that your ui-sortable has one extra div child at its end,
with class triangle-cards that does not match any item of your model.
Can you provide an example code pen?
This might be related with margins or relative/absolute positioning of the
elements by the css classes that you are using.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Hi there, any feedback on this? Did you managed to fix it for your use case?
Have been able to create a codepen/jsfiddle example?
Have you tried using the b placeholder option?
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
I'm closing this for now since it has been marked as jquery-ui related and
there has been no feedback for the last few weeks. Even if this is not the
most appropriate place to discuss jquery-ui related issues, please feel
free to reopen & post any extra info or a possible solution.

>
> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
