### ISSUE TITLE
TypeError: element.sortable is not a function

### ISSUE THREAD

**Issue by mcblum** [angular-ui/ui-sortable#425]
Any idea what might be causing this? I've tried everything I can think of.

Edited to add the things I'm sure of:

1) jQuery is loaded before jQuery UI by 10,000 lines or so.
2) angular-ui-sortable is being loaded correctly.
3) The code appears to be correct in the view:

 ````<ul ui-sortable="galleryCtrl.sortableOptions" ng-model="galleryCtrl.gallery.images" class="gallery--images --index">
                        <li ng-repeat="image in galleryCtrl.gallery.images">
                            <img src="{{image.path}}{{image.filename}}?w=300&h=300" alt="">
                        </li>
                    </ul>````

**Comment by thgreasi** [comment]
Have you included jquery-ui as shown in the examples found in README?

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by mcblum** [comment]
I thought I had, but it turns out everything I was doing was being messed with because I'm loading all of this via Bower. Overriding the dependencies for Angular in bower.json did the trick. For those who might encounter this, you'll need to make sure you load jQuery before Angular and if you're using Gulp and something like main-bower-files you'll need to add this to your bower.json:

````
"overrides": {
    "angular": {
      "dependencies": {
        "jquery": "*",
        "jquery-ui": "*"
      }
    }
  }
````

**Comment by thgreasi** [comment]
I'm glad you found your way around.
Thanks for posting back your findings!

**Comment by mcblum** [comment]
Thanks for your quick reply and for a great repo.

**Comment by wautersj** [comment]
When I include the 4 dependencies of jquery-ui seperatly as described: core, widget, mouse & sortable ... I get an error, and my app won't run. When I load the entiry jquery-ui library, the app runs fine.

I don't like loading libraries i'm not using. Do you have an idea why this is happening?

**Comment by thgreasi** [comment]
Is there any chance that you are not including them in the proper order?
Or, is there any chance that an other part of your app needs an extra jQUery-UI module?

**Comment by wautersj** [comment]
I don't think so:
According the what I'm reading, they are in the proper order, No?

![screen shot 2017-05-18 at 16 01 56](https://cloud.githubusercontent.com/assets/4070167/26205874/63c7b9a4-3be3-11e7-98e0-3e675c5e3d60.png)

These are the first libraries i'm loading before everything else. And only fails to work this way.

![screen shot 2017-05-18 at 16 00 36](https://cloud.githubusercontent.com/assets/4070167/26205831/3b00ee6e-3be3-11e7-9bab-495204343215.png)

When I use **'./bower_components/jquery-ui/jquery-ui.js'** instead of those 4, it runs fine.

**Comment by thgreasi** [comment]
What version are you using?
`core.js` says on top `// This file is deprecated in 1.12.0 to be removed in 1.13`.
Please try including `version.js` first, instead of `core.js`.
