### ISSUE TITLE
connectWith on multiple tbody's when one list is empty

### ISSUE THREAD

**Issue by jgr3go** [angular-ui/ui-sortable#428]
See http://codepen.io/jgr3go/pen/vLQQLM

I believe this meets all the rules, but I can't for the life of me figure out how to go about doing it. I have a scenario where I have multiple `tbody` tags in a table, with ui-sortable attached to each of them.  They each have `<tr ng-repeat=...>` as their only child, and the options allow you to connect the two `tbody`s.  It works (as in the above example) as long as you have at least one item in each list. 

However, if you have no items in one of the lists (i.e. if you drag "Facebook (b)" to the first list), you can't drag anything into the empty list.  

Any ideas how I can get this to work? I can't manually add another shell `<tr>` because then indexing breaks, and as far as I can tell this is a valid use-case within the rules of this library, but I can't figure out a way to make it work.

**Comment by garymazz** [comment]
I have cludge it up.. if you force a white space character in the sortable tag's data before the `<tr ng-repeat=...>` it sometimes works.

**Comment by eduardodgarciac** [comment]
Add this between tbody tags
`<tr ng-if="!list2.length" class="sort-disabled">
      <td colspan="2">No records</td>
</tr>`

And this to the sortableOptions
`handle: function() {
      //Add sortable class to the tbody
      $('.sortable').sortable({items: ">*:not(.sort-disabled)"});
},`

Or just a empty td, whatever fit to you.

**Comment by thgreasi** [comment]
Sorry it took me so long to answer on this.

In non-table use cases, I tend to use something like `ng-class="{ 'apps-container-empty': !list2.length }"` on the sortable list and then add some padding and probably some placeholder text using some css `.apps-container-empty { /*...*/ }` and `.apps-container-empty:after { content:'Empty!';  /*...*/ }`. This way we minimize the manipulations to the elements that ui-sortable manage.
Unfortunately this does not work well with the `tbody` element, so the solution @eduardodgarciac mentioned, might be the best alternative approach. :+1: Is the proposed workaround working for you?

**Comment by thgreasi** [comment]
Have you managed to make it work for your use case? Should we mark it as
resolved?

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Closing this for now.
Please feel free to re-open if you are still troubled.
In case you have a working solution and think that it might be useful to
others as well, feel free to open a PR adding a codepen example in the
repo's README.
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by jgr3go** [comment]
Oh yeah sorry, this is fine to close. I'll put together an example soon and
pull, hopefully it'll help someone else.
