### ISSUE TITLE
Multiple lists. How to know in which list were dropped the item?

### ISSUE THREAD

**Issue by eduardodgarciac** [angular-ui/ui-sortable#433]
I have multiple tables and the sortable function is working perfectly. I want to know in which table where dropped the item. Any idea?

**Comment by thgreasi** [comment]
You can use the [droptarget](https://github.com/angular-ui/ui-sortable/blob/master/API.md#droptarget) or the [droptargetmodel](https://github.com/angular-ui/ui-sortable/blob/master/API.md#droptargetmodel) properties of the `ui.item.sortable` object. The `ui` object can be accessed as the second variable of any the `ui-sortable` callback.
You should probably better use:
* the `update` callback, if you need to revert a sorting
* the `stop` callback, if you only want to act after the sorting has finished
