### ISSUE TITLE
ui.item.sortable properties are undefined

### ISSUE THREAD

**Issue by mdennis10** [angular-ui/ui-sortable#443]
I getting undefined properties when calling ui.item.sortable from my update method. I want to get the information about the item i'm moving and the one its replacing. How can I fix this?

     `$scope.sortableOptions = {
            update: function (e, ui) {
                console.log(ui.item.sortable);
             }
         };`

    `<tbody ui:sortable="sortableOptions" ng:model="data">
                    <tr data-ng-repeat="person in data">
                        <td>{{person.Grp}}</td>
                        <td>{{person.MicID}}</td>
                        <td>{{person.Name}}</td>
                        <td>{{person.Description}}</td>
                        <td>{{person.PPersonID}}</td>
                        <td>
                            <a data-ng-href>
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                </tbody>`

**Comment by thgreasi** [comment]
Since this doesn't happen in the codepen exampled found in README, can you provide one that matches your use case?

**Comment by fatkhanfauzi** [comment]
Same issue with mine:

![image](https://cloud.githubusercontent.com/assets/2447205/13922233/591d2ce8-efb6-11e5-9a4e-e36ea788def6.png)

**Comment by thgreasi** [comment]
When `element.sortable is not a function` shows up, then you probably are including jquery &/ jquery-ui in the wrong order. Please take a look at the examples [provided in README](http://codepen.io/thgreasi/pen/jlkhr) and provide a fork that demonstrates the problem with your use case.

@mdennis10 I just forked the simple example and [the properties ui.item.sortable appear normally](http://codepen.io/thgreasi/pen/pyeKZJ). Please provide an example with your use case.

**Comment by fatkhanfauzi** [comment]
yes, on my environment was caused of the import order, since i used webkit i should reorder the dependencies. Finally, it works.

**Comment by mdennis10** [comment]
@thgreasi I added a snippet of my code above the and result I'm getting is the following:

![capture](https://cloud.githubusercontent.com/assets/3623620/13956246/f6193352-f015-11e5-900f-a0866eaf6d82.PNG)

**Comment by thgreasi** [comment]
Actually, as you can see in the first line, the properties are not null at the moment that they get printed.
They get nullified (to eliminate any possible memory leadks) as  soon as the sorting ends and that's the reason that when you inspect the logged object you see the same properties `undefined`.
If you set breakpoints to your code, then you should be able to inspect the values of these properties.
In [this example](http://codepen.io/thgreasi/pen/pyeKZJ) you can see that I'm able to log each property in its own line.

In case that you still need access to some of them after the sorting ends, you should store them in your own variables (or even clone the whole object).

**Comment by developmedev** [comment]
run this
 npm i jquery-ui-bundle

add this to 
angular.json
under scripts
 "node_modules/jquery-ui-bundle/jquery-ui.min.js",

this do this in your component
import * as $ from 'jquery-ui-bundle/jquery-ui.min';
declare var $: $

ngOnInit(): void {
  var self=this;
  $("#sortable").sortable({
    start: function(e, ui) {
      // creates a temporary attribute on the element with the old index     
  },
  update: function(e, ui) {
      // gets the new and old index then removes the temporary attribute
  }
  }); 
}

make sure u have an element with id sortable

**Comment by thgreasi** [comment]
@teezy7 is that a bug report, do you have a question on that or is it a suggestion?
