### ISSUE TITLE
Everything in ui.item.sortable is undefined even if we keep references in the code

### ISSUE THREAD

**Issue by MadJlzz** [angular-ui/ui-sortable#448]
Hello,

I am facing a strange issue with the callback functions. In fact, I've just followed the [API.md](https://github.com/angular-ui/ui-sortable/blob/master/API.md) and I've seen that the properties of ui.item.sortable object are cleared right after the stop callback fires. I took my precautions by storing those references in my own variables but everything is still empty as shown above.

![image](https://cloud.githubusercontent.com/assets/1558564/14352142/5ab80774-fcd3-11e5-8231-4222527959dd.png)

![image](https://cloud.githubusercontent.com/assets/1558564/14351936/6544e7c6-fcd2-11e5-8f8a-be977a06c5b8.png)

**Comment by thgreasi** [comment]
Related to #443.
You should keep references to each individual property eg ui.item.sortable.sourceModel.
An other approach would be to do a shallow copy of the ui.item.sortable , for example by using someting like `var tmpSortable = $.extend({}, ui.item.sortable);`. Just remember to do so inside the callback the sortable state interests you.

**Comment by thgreasi** [comment]
Closing for now, feel free to re-open (preferably with a code-pen example) if you still face problems.

**Comment by MadJlzz** [comment]
Oh well, how did I just miss that ? Thanks!

**Comment by thgreasi** [comment]
For reference, duplicate  #443 .
