### ISSUE TITLE
cursorAt not working for the first time

### ISSUE THREAD

**Issue by krema** [angular-ui/ui-sortable#451]
Hi there, 

I'm trying to set the cursorAt options in the start event and recognized that this option will be just ignored the first time I try to sort the element. But when I try it a second time the cursorAt option everything goes fine and the cursor will be set.

    start: function(event, ui) {
        // Logic to change the size of the ui.item element dynamically

        // Change cursorAt to center the cursor
        $(this).sortable("option", "cursorAt", { left: ui.item.width() / 2, top: ui.item.height() / 2 });
    }

My question is whether there is something missing in the initializing of ui-sortable and its element. I can see that ui.position and ui.offset is undefined for the first time. I tried to set them but with no luck. 

Any ideas?
Thanks

**Comment by krema** [comment]
Sorry about that. After investigating this issue I found that this is related to jquery-ui. 
I created a bug ticket there. 

https://bugs.jqueryui.com/ticket/14952#ticket

**Comment by thgreasi** [comment]
:+1:
