### ISSUE TITLE
Using ui-sortable with an ng-repeat that is filtered - drag and drop doesn't work.

### ISSUE THREAD

**Issue by shawngong** [angular-ui/ui-sortable#452]
I created two fiddles to showcase the issue.

The first, uses no filter - and drag and drop works as intended.

http://jsfiddle.net/Lvc0u55v/2887/

The second uses a filter - and the drag and drop does not work (the items just go back).

http://jsfiddle.net/Lvc0u55v/2886/

Removing the ng-model will cause the filter drag and drop to work as intended, but I am not sure if this is a bug or intended behaviour?

**Comment by thgreasi** [comment]
As noted in README, you have to move the filtering in the controller,
otherwise the element matching with the model items breaks. Take a look at
the filtering examples found in README.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
