### ISSUE TITLE
all values for ui.item.sortable undefined in stop method

### ISSUE THREAD

**Issue by kyleicebreaker** [angular-ui/ui-sortable#458]
angular v1.4.5

Can reproduce here: http://codepen.io/thgreasi/pen/KtsFH

![screen shot 2016-05-11 at 4 49 37 pm](https://cloud.githubusercontent.com/assets/14184138/15200101/bf9331f2-1798-11e6-8564-32fb16830627.png)

**Comment by kyleicebreaker** [comment]
Found my issue.

**Comment by thgreasi** [comment]
I'm glad you found your way around. Do you have any suggestion that could improve the docs?
For reference, duplicate  #443 #448 .
