### ISSUE TITLE
Memory leak in js heap area

### ISSUE THREAD

**Issue by Kanti1702** [angular-ui/ui-sortable#463]
Need to destroy ui-sortable components, as it recreate HTMLTableElement everytime I open the screen with ui-sortable.

**Comment by thgreasi** [comment]
Please be more descriptive with your use case or even better provide a codepen example along with steps to reproduce the leaks (or at least a screenshot that has some hints about the leak).
UI-Sortable actually does destroy all element references on the `ui.item.sortable` object.

Discussions about leaks existed in the past (#185, #439) but didn't prove that UI-Sortable was leaking.
As noted in #185:
> A good example code to test this out should be the [`Tree with dynamic template`](http://codepen.io/thgreasi/pen/uyHFC) example of the README file.

where UI-Sortable instances are constantly created and destroyed with every sorting between the levels of the tree.

**Comment by thgreasi** [comment]
Also please provide the versions of the libraries that you are using.

**Comment by thgreasi** [comment]
Please re-open with more info.
