### ISSUE TITLE
Unknown provider: ui.sortableProvider <- ui.sortable

### ISSUE THREAD

**Issue by weird-dreams** [angular-ui/ui-sortable#468]
Hi there,
maybe it is my fault.
I setup a VS project and icluded by NuGet jQuery and jQuery.UI (both 1.10).
Then added angular-ui sortable.

Here is my bootstrap code (typescript):
`this.mAngularApp = angular.module(this.moduleName, "ui.sortable");`

_How may I fix this bootstrap error?_
`Unknown provider: ui.sortableProvider <- ui.sortable`

Thank you,
Andi

**Comment by thgreasi** [comment]
It seems that the ui-sortable js file is not (properly) included to the web page.

**Comment by seusofthd** [comment]
Did you solve it? I met the same problem

**Comment by thgreasi** [comment]
Hi @seusofthd, since I never got further feedback, how are you including angularjs & ui-sortable?
That specific error message appears when a module is requested and is not part of the available/known modules. (That applies both in plain JS and TypeScript as well.)

**Comment by seusofthd** [comment]
I just followed the examples without changing anything

**Comment by thgreasi** [comment]
Unfortunately, I can't really help if nobody shares any code.

**Comment by thgreasi** [comment]
Any feedback on this?

> --
*Thodoris Greasidis*

**Comment by thgreasi** [comment]
Closing this for now, feel free to re-open if necessary.
