### ISSUE TITLE
get value / object of dropped item

### ISSUE THREAD

**Issue by jmls** [angular-ui/ui-sortable#469]
In the stop event, I need to be able to get the *angular* array item that was dropped so that I can change some attributes

Is there any mechanism (index of new object, or the actual object, or array change) that I could use in ui-sortable ?

**Comment by thgreasi** [comment]
Take a look at the API.md and the canceling examples. You probably need `ui.item.sortable.model`.

**Comment by jmls** [comment]
can't believe I missed that. thanks, and sorry ;)

**Comment by thgreasi** [comment]
np gl gf
