### ISSUE TITLE
Weird behaviour when trying to sort element1 to element2.

### ISSUE THREAD

**Issue by eldimious** [angular-ui/ui-sortable#470]
There is a strange behaviour when i am trying to drag and sort a ul. it recognizes when y move an element from position 2 to position 1 and update the ng-model, but not recognizes the opposite and doesnt update the ng-model. In both occasions all the events are fired, but when i am trying the occasion from position 1->2 the ng-model is not updated in the stop event.
 I have use the latest version of angular-ui-sortable and the 2.2.4 jquery's version and this is my code.

`<ul ui-sortable="sortableOptions" ng-model="native.tiles">
      <li ng-repeat="tile in native.tiles">
        .......
      </li>
    </ul>`

**Comment by thgreasi** [comment]
The code that you provided seems correct and I wasn't able to reproduce :-/
It would be great if you could fork the [Connected sortables demo](http://codepen.io/thgreasi/pen/uIBKb) found in README to provide your use case.

**Comment by eldimious** [comment]
Hey, it happens exactly the same error as in this jsfiddle -> [.](http://jsfiddle.net/gw5fp/37/)
Try to move the "one" element to "two" element and the opposite and take a look at the div under the ul.

**Comment by thgreasi** [comment]
I'm sorry but `angular-ui.min.js` is v0.4.0 which is two year old and doesn't support angular v1.2+.
The angular-ui project has been split to separate modules. Please try one of the examples found in README and re-open if you still face the same issue.
