### ISSUE TITLE
Static Row 

### ISSUE THREAD

**Issue by cburman01** [angular-ui/ui-sortable#471]
Is there a way to maintain a static row for a specific model in the list?   

Example: 
a
b
C
d  
e

If you move e  above e, C goes to row 4. 
a
b
e
C
d

I want C to always be row 3.    

I've tried many things, mostly just manipulating the models in the various events, but i'm thinking there must be an easier way.

**Comment by thgreasi** [comment]
For the use cases that I faced so far, manipulating the model was an acceptable solution.
I think that what you are looking for is described in #274 that is still open.
Please re-open if I misunderstood something.

**Comment by cburman01** [comment]
Thanks @thgreasi
