### ISSUE TITLE
Can you add support for Angular2?

### ISSUE THREAD

**Issue by Ajeey** [angular-ui/ui-sortable#474]

**Comment by thgreasi** [comment]
README states:
> Early adopters of [Angular2](https://angular.io/) can use the  [ng2 branch](https://github.com/angular-ui/ui-sortable/tree/ng2).

Are you facing issues with it?
I haven't yet done a release since I'm hesitant about using the same npm package with just a version increase or using a new repo like ui2-sortable.
Waiting for your feedback.

**Comment by thgreasi** [comment]
@Ajeey Did the ng2 branch work for you?
Any feedback?

**Comment by Ajeey** [comment]
@thgreasi Will be trying out this weekend and update you. Thanks

**Comment by thgreasi** [comment]
Any feedback on this?
-- 
*Thodoris Greasidis*

**Comment by thgreasi** [comment]
Closing this for now, feel free to re-open if necessary.
