### ISSUE TITLE
The list won't update after delete/add item

### ISSUE THREAD

**Issue by insmark** [angular-ui/ui-sortable#475]
I modified this [demo](http://plnkr.co/edit/XPUzJjdvwE0QWQ6py6mQ?p=preview), I added a Move items button to add the first two items from Players to Team, and then removed first two items from Players. After click the button, but the both lists don't show the updated list.

Pen: [http://codepen.io/insmark/pen/grvGVX](http://codepen.io/insmark/pen/grvGVX)

**Comment by thgreasi** [comment]
If you use `onclick` then you should also [use `$apply`](http://codepen.io/thgreasi/pen/rLJvWW).
Depending on the use case, most of the time you will probably better use `ng-click` instead, since it doesn't require the manual `$apply` call.

**Comment by insmark** [comment]
Thanks a lot!
