### ISSUE TITLE
Pass parameter to sortableOptions

### ISSUE THREAD

**Issue by Znow** [angular-ui/ui-sortable#481]
Heya

Is it possible use the ui-sortable="sortableOptions" as a method? And how?

I need to pass parameter to sortableOptions.

I.e. 
```html
<ul ui-sortable="sortableOptions(param1, param2)">
</ul>
```

I've searched alot in the issues, could not find anything related.

Kind regards

**Comment by thgreasi** [comment]
You should be able to pass a full json:
```html
<ul ui-sortable="{ helper: myScopeVar }"></ul>
```
OR you can create a factory-method on your scope, in your controller:
```html
<ul ui-sortable="createSortableOptions(param1, param2)"></ul>
```
```js
$scope.createSortableOptions = function (param1, param2) {
  return {
    helper: param1,
    placeholder: param2
  };
}
```

**Comment by Znow** [comment]
@thgreasi Fantastic, thanks alot!

**Comment by Znow** [comment]
@thgreasi Tried your example, after I wrote my previous answer :p

It does not seem to work though.

I'm getting: "Error: $rootScope:infdig Infinite $digest Loop"

```
10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function (c,e,f,g){f=d&&g?g[0]:a(c,e,f,g);return b(f,c,e)}","newVal":{"helper":"test"},"oldVal":{"helper":"test"}}],[{"msg":"fn: function (c,e,f,g){f=d&&g?g[0]:a(c,e,f,g);return b(f,c,e)}","newVal":{"helper":"test"},"oldVal":{"helper":"test"}}],[{"msg":"fn: function (c,e,f,g){f=d&&g?g[0]:a(c,e,f,g);return b(f,c,e)}","newVal":{"helper":"test"},"oldVal":{"helper":"test"}}],[{"msg":"fn: function (c,e,f,g){f=d&&g?g[0]:a(c,e,f,g);return b(f,c,e)}","newVal":{"helper":"test"},"oldVal":{"helper":"test"}}],[{"msg":"fn: function (c,e,f,g){f=d&&g?g[0]:a(c,e,f,g);return b(f,c,e)}","newVal":{"helper":"test"},"oldVal":{"helper":"test"}}]]
```

```html
<ul ui-sortable="createSortableOptions('test')">
</ul>
```

```js
$scope.createSortableOptions = function(param1)
            {
                return {
                    helper: param1
                    
                }
            }
```

**Comment by thgreasi** [comment]
@Znow my bad, didn't think at all about angular's equality check... As you guess, each object returned is different and has a different reference and that resulted the infinite digest loop.
If your use case is all about having an argument passed to the options from the HTLML (view) then:
* Use a factory function with result caching like in [this example pen](http://codepen.io/thgreasi/pen/QEJrmO). Depending on your use case you might be able to just keep the last result of the factory, or
* use a separate wrapper directive, or
* [use `ng-init` to declare a variable on your scope, then watch it in the controller and finally have the watcher update the `sortableOptions` object](http://codepen.io/thgreasi/pen/EyOvZJ). Keep in mind that depending on your use case, you might also be able to avoid adding the `$watch` altogether and use the scope variable directly during the creation of the `sortableOptions` object.
