### ISSUE TITLE
Error with jquery-ui 1.12.0

### ISSUE THREAD

**Issue by MarbleDaemon** [angular-ui/ui-sortable#482]
Hello,

I've recently update jquery-ui to 1.12.0 and the plugin doesn't work anymore. Every time I click on a row, I receive the following error:

![image](https://cloud.githubusercontent.com/assets/4795076/18042158/5fb80224-6de9-11e6-980c-33aeb129b0de.png)

Please help me fix the problem.

Thank you.

**Comment by thgreasi** [comment]
Were you able to resolve the issue? What was troubling your setup?

**Comment by MarbleDaemon** [comment]
Hello,

I was my mistake not to include needed widgets from jquery-ui. It's a no bug.
