### ISSUE TITLE
ui.sortable: jQuery should be included before AngularJS!

### ISSUE THREAD

**Issue by Chienle** [angular-ui/ui-sortable#485]
Hi guys,
Today is a beautiful day, I got a issue when using ui-sortable "ui.sortable: jQuery should be included before AngularJS!",

Jquery version : v1.6.4

in my controller
var app = angular.module('app', ['ui.sortable',...]);

In my view

`<div ui-sortable ng-repeat="answer in bwr.content.data.answers">
    <div style="border:1px; margin:5px;">{{answer}}</div>
</div>`

So, can you please help me ?

**Comment by thgreasi** [comment]
Hi there.
It's a rainy day here in Greece.
All you have to do is to place the script tag that includes jQuery to your page before the script tag of AngularJS. That's started in README and degenerated in the examples. There is also an example demonstrating how to achieve when using requirejs, defining a manual dependency. Lastly, some others issues asking about this already exist, giving it a search might give you even more info.

**Comment by thgreasi** [comment]
Closing this for now. Feel free to reopen in any case.
