### ISSUE TITLE
Remove items from ui.item.sortable.droptargetModel

### ISSUE THREAD

**Issue by P4trik** [angular-ui/ui-sortable#486]
Hey *,

is it possible to remove items from the ui.item.sortable.droptargetModel array?

If I do that, the element doesn't disappear from the list on the surface.

`update: function (e, ui) {
                console.log(ui);
                console.log(ui.item.scope());
                ui.item.sortable.droptargetModel = []
            }`

If I remove the element directly from my origin list, it work's fine but then I have to loop through the entire tree to find the property.

**Comment by thgreasi** [comment]
Hi there.
Since `droptargetModel` is a reference, you should use `ui.item.sortable.droptargetModel.length = 0;` to clear the list, or `splice()` to remove specific items. Feel free to re-open in any case :)

**Comment by P4trik** [comment]
Thanks! Works great! :-)
