### ISSUE TITLE
Access to parent repeater item in update event

### ISSUE THREAD

**Issue by P4trik** [angular-ui/ui-sortable#487]
Hey,

I got the follow scenario:
`<div ui-sortable ng-model="board.shelves" class="shelf" ng-repeat="shelf in board.shelves">
                    <ul class="apps-container shelfContainer" ui-sortable="sortableOptionsList[0]" ng-model="shelf.products">
                        <li ng-repeat="product in shelf.products">
                            <span>{{product.name}}</span>
                        </li>
                    </ul>
                </div>`

Is it somehow possible to access the shelf property of my outer repeater, inside the update event of the sortableOptionsList[0] setting? Update event supplies me the list of UL-Elements but I have to access the element above.

Hope it's understandable :-/

Thanks for great support!

**Comment by thgreasi** [comment]
Unfortunately, this has to be done in the controller, by having it assigned to a local `var`. In case you have multiple lists, you should probably also check which one contains the moved item.

A hacky way that will not work on DisabledDebugInfo invironment would look like this:
```js
ui.item.source.scope().shelf
```
PS : Didn't actually tested the above code, but it demonstrates the concept of this hacky approach.
