### ISSUE TITLE
Cancelling sort using custom helper causes list to display in incorrect order

### ISSUE THREAD

**Issue by nathanialle** [angular-ui/ui-sortable#491]
Hi, I forked the simple codepen to show my issue.

I have to create a custom helper in my code to fix the offset scroll issue. I have an issue when after I  cancel the sort a few times.

See codepen

[Codepen](http://codepen.io/anon/pen/qqjvap)

If you drag the top item to the bottom of the list 3 times it ignores the cancel event. Now the list is displayed incorrectly and if you try sorting other items you see the log shows the model item orders do not match the list displayed in the left hand side.

Been trying to work out what is going on to but am none the wiser.
Please advise.

**Comment by thgreasi** [comment]
I was able to replicate. I will try to investigate during the weekend.

**Comment by thgreasi** [comment]
Resolved by #493 and released as v1.5.1 .
Please confirm that it works for you.

**Comment by nathanialle** [comment]
Works perfect, thks loads
