### ISSUE TITLE
Vertical scroll jumps on drag element on the bottom of a page

### ISSUE THREAD

**Issue by krzysiek-kr** [angular-ui/ui-sortable#495]
It occur when an array of sortable elements is long enough that vertical scroll appears.
If You scroll down the page to the bottom and drag one of the elements the scroll makes some jump.
I think it is caused by that first of all the dragged element is removed from DOM and length of the page is decreased so the vertical scroll jumps and than the placeholder is added and the page length returns to its previous value but the vertical scroll stay at its current position.

**Comment by thgreasi** [comment]
[I think that this one is already answered](https://github.com/angular-ui/ui-sortable/search?q=Vertical&type=Issues&utf8=%E2%9C%93) and is not related with this library but is a jquery-ui issue.
Feel free to reopen in any case.
