### ISSUE TITLE
Sorting doesn't update models

### ISSUE THREAD

**Issue by TheBosZ** [angular-ui/ui-sortable#5]
Hey, I've been trying to figure this out all day, but I can't.

I've got a three-level nested model system going and I want to sort at each level.

I've got it set up so everything's working, except that the models don't update after the sort.

Fiddle: http://jsfiddle.net/Gv7fr/6/

To see the problem, add a "Menu" and then add a "Group", those are the first two levels.

Then add two or more "Items" to that group. Put in some Information so you can see what's happening.

Drag to reorder the items, the model isn't changed below.

Notes:
I am (apparently) using Angular 1.1.4 and I'm using a version of this plugin from yesterday.

I've tried updating the plugin, but that seems to make all the options not work at all, and I need them.

**Comment by nicolae-olariu** [comment]
We had the same problem.
Fix for anyone interested: instead of using the `update` event, we've used the [stop](https://api.jqueryui.com/sortable/#event-stop) event and everything worked like a charm.

**Comment by thgreasi** [comment]
@nicolae-olariu :+1:

**Comment by jpodpro** [comment]
i'm going to suggest that the custom 'update' function appears to be called before the model is actually updated.

**Comment by thgreasi** [comment]
I think that this it's documented in README with:
> Any model changes that happen inside the available callbacks, are applied right after the stop event.

And:
> update is the appropriate place to cancel a sorting, since it occurs before any model/scope changes but after the DOM position has been updated. So ui.item.scope and the directive's ng-model, are equal to the scope before the drag start.

**Comment by evaldasjab** [comment]
yessss, adding stop event together with the update event made the scope update, woohoo! :+1:

**Comment by igorkemack** [comment]
You can access to dragged model in update callback in this way:
`...
  "update": function(e, ui) {
    var draggedModel = ui.item.sortable.model;
  }
...
`
