### ISSUE TITLE
Regression: 0.16.0 droptargetContext is undefined

### ISSUE THREAD

**Issue by realityfilter** [angular-ui/ui-sortable#500]
With version 0.16.0 after dropping the sortable item int the new location this error appears in the console.

`TypeError: undefined is not an object (evaluating 'droptargetContext.scope')`

The corresponding line is:

`sortable.js:332: ui.item.sortable.droptargetModel = droptargetContext.scope.ngModel;`

This seems to be when using `data-ui-sortable` instead of `ui-sortable` as attribute name.

**Comment by thgreasi** [comment]
Thaks for reporting and sorry for the inconvenience. I'm on it.
