### ISSUE TITLE
Not sorting properly

### ISSUE THREAD

**Issue by digitalrep** [angular-ui/ui-sortable#503]
http://codepen.io/anon/pen/YNeKZp

Is it the versions of jquery etc. I'm using? Or something else?

**Comment by thgreasi** [comment]
Strange or no results with jQuery v3.0 has been reported before. Please use
v3.1. Also I didn't check  the version of ui-sortable that you are using.
The examples found in README work using jQuery v3.1, so I would suggest you
to use them as a good starting point.

-- 
*Thodoris Greasidis*

**Comment by thgreasi** [comment]
Adding a `track by $index` in the `ng-repeat` resolved the issue.

**Comment by digitalrep** [comment]
Oh thanks I will try that out. Thanks so much for letting me know.
