### ISSUE TITLE
Sorting doesn't work properly with jquery 3.1 and jquery-ui 1.12.1 

### ISSUE THREAD

**Issue by watzak** [angular-ui/ui-sortable#505]
Hi

I have used your plugin with jquery 2.2.2 and jquery-ui v1.12.0!
It just worked perfect!

But after updating to jquery 3.1, the sorting doesn't work properly!

Please check out my demo site 
https://jsbin.com/fifiwiruga/1/edit?html,js,output

![screen](https://cloud.githubusercontent.com/assets/8505970/22878429/0f29f3d8-f1da-11e6-8ced-2ec374f8cd19.gif)

**Comment by thgreasi** [comment]
That's strange, since the examples in README work fine. EG: the simple sorting example](http://codepen.io/thgreasi/pen/wzmvgw). What versiuon of ui-sortable are you using? Can you try updating?

**Comment by thgreasi** [comment]
Also the jsbin example was not running at all for me.
![screen shot 2017-02-13 at 11 57 26](https://cloud.githubusercontent.com/assets/1295829/22878825/e6c07c82-f1e3-11e6-80b4-38de40a1b5df.png)

**Comment by watzak** [comment]
@thgreasi : Please use following url => https://jsbin.com/fifiwiruga/1/edit?html,js,output

**Comment by thgreasi** [comment]
Still can't drag anything.

**Comment by thgreasi** [comment]
Please update your ui-sortable version and avoid using `ng-class` on the `ng-repeat`ed element.
Please use the provided examples as a reference point.

**Comment by watzak** [comment]
Hello @thgreasi 

I have now made changes as described!
- newest sortable-ui version
- removed ng-class

But it's still not working properly! 
Please check out by yourself
=> https://jsbin.com/boqucaloka/1/edit?html,js,output

Switch one (1) with second (2) element and u will find 1 at the bottom :(

Thanx in advance

**Comment by thgreasi** [comment]
Is [this](https://jsbin.com/suveqimuco/1/edit?html,js,console,output) working as expected?

**Comment by watzak** [comment]
no, unfortunately not ;)
Expected: If I switch one with second item, then second item would become first and first would become second
Right now I switch one with first: Second becomes first! Thats ok! But first becomes last item! That's not what I would excpect to behonest ;)

=> https://jsbin.com/boqucaloka/1/edit?html,js,output

**Comment by watzak** [comment]
ah now I clicked on your sample! Yes it looks good ;) I will check your sample  => https://jsbin.com/suveqimuco/1/edit?html,js,output

Thanx in advance ;)

**Comment by watzak** [comment]
@thgreasi : Thanx a lot ;) 

with track by $index it's just working ;)
