### ISSUE TITLE
can we have sortable and drag and drop at the same time

### ISSUE THREAD

**Issue by jeevasusej** [angular-ui/ui-sortable#508]
I have list a and list b.

I want to sort the items in the list a.
I don't want to sort the items in the list b but wants to drag item from them and drop them in list a.

How to do that?

**Comment by jeevasusej** [comment]
Found the solution. 
I am closing this issue.

**Comment by thgreasi** [comment]
Was this reopened by accident? Should we close it again?

**Comment by jeevasusej** [comment]
No. I don't know How to solve this. Still I am getting the issue.

**Comment by thgreasi** [comment]
Please check out the [Draggable-Sortable like interaction](http://codepen.io/thgreasi/pen/mAxdxk) found in README. I think that the demonstrated use case is very close to what you are trying to do.
Closing for now. Feel free to re-open in any case.
