### ISSUE TITLE
After api call, properties are undefined

### ISSUE THREAD

**Issue by jeevasusej** [angular-ui/ui-sortable#509]
I want to make api call. After successful return, i want to do some actions on the objects in the sortable.

But I am getting undefined.

The following becomes undefined
```
ui.item.sortable.cancel
ui.item.sortable.sourceModel
```

**Comment by jeevasusej** [comment]
https://github.com/angular-ui/ui-sortable/issues/448

**Comment by thgreasi** [comment]
:) I'm glad you found your way around!
