### ISSUE TITLE
No dropzone exists in clone use case when data source is an ng-repeat and not fixed object

### ISSUE THREAD

**Issue by JakeMauch** [angular-ui/ui-sortable#519]
So most of the examples we use are fixed, hardcoded objects.  My data consists of a variable number of ui-sortable lists which must be able to clone to a single ui-sortable.  Currently, in the clone use case, attempting to drag from one of these other ui-sortables into the target will render a dropzone of undefined and as a result fail to move anything properly.

Sorry if I fail to tag this properly, not the most experienced with github's issue tracker.

**Comment by thgreasi** [comment]
Hi there!
Can you fork one of the examples found in README and post it to showcase you use case?

**Comment by thgreasi** [comment]
Any feedback on this?

**Comment by JakeMauch** [comment]
Sorry, I'll try to get some data soon but I've been forced to move on in my
project

**Comment by thgreasi** [comment]
Updated the [cloning example found in README](https://codepen.io/thgreasi/pen/jrzOLA) to work with a dynamic number of sources.
Closing for now, feel free to re-open in any case.
