### ISSUE TITLE
Notes on README files update

### ISSUE THREAD

**Issue by migacz1125** [angular-ui/ui-sortable#531]
In notes part of description is information  to load  core, widget, mouse & sortable. In jquery-ui since 1.12 version core.js is deprecated and to be remove in 1.13 version. That will be nice to add some information about this.

**Comment by thgreasi** [comment]
Thanks for the heads up!

**Comment by thgreasi** [comment]
Updated README to point to the new dependencies, have an up-to-date custom builder url & contain an updated jsdelivr min dependencies url.
Again, thanks for the heads up.
