### ISSUE TITLE
'$modelValue.splice' let me get a wrong currentContainer ?

### ISSUE THREAD

**Issue by 10081677wc** [angular-ui/ui-sortable#533]
Hi,

```
ui.item.sortable.moved = ngModel.$modelValue.splice(ui.item.sortable.index, 1)[0];
```

This code in `callbacks.remove` may be some problems?
When the dom changed cause by $modelValue, I sometimes get a wrong currentContainer.

**Comment by thgreasi** [comment]
Can you fork one of the provided examples to reproduce the issue you are facing?

**Comment by thgreasi** [comment]
Please retest against the just released v0.17.2.

**Comment by 10081677wc** [comment]
Thank you for your advice, 
unfortunately, the same problem occurs in the v0.17.2,
and I find the question https://github.com/angular-ui/ui-sortable/issues/534, 
it' s a similar situation to mine,
I will try to reproduce the issue :)

**Comment by 10081677wc** [comment]
I found out that my problem was different from #534,
I try to reproduce...but..."rawgit.com/angular-ui/ui-sortable/master/src/sortable.js" always loaded failed, maybe it's my network problem.
I'll leave a message after the reproduction.

**Comment by 10081677wc** [comment]
Hi,
I find the problem lies in 'track by $index'.

**Comment by thgreasi** [comment]
Thanks for sharing!
