### ISSUE TITLE
when drop item into sortable but it dropped another same sortable under it

### ISSUE THREAD

**Issue by soonwait** [angular-ui/ui-sortable#534]
means that i have a layout sortable div which contains some items... but this div used only to show layout READONLY than configured

then, i user to configure the layout, it open an modal dialog contains another sortable div

two sortable with same style but a 'configing' class

when drag items and drop into sortable of dialog, but the ites falls into READONLY sortable....sad!

**Comment by thgreasi** [comment]
I'm not sure whether I understood your use case right, but please check your `ng-model` and your `connects-to` options. A fork of a code example would be great.

**Comment by thgreasi** [comment]
Please retest against the just released v0.17.2.

**Comment by soonwait** [comment]
thanks， i ve changed the both connectWith to defferent, then solve my problems.
