### ISSUE TITLE
Not Working in IPad,IOS

### ISSUE THREAD

**Issue by ajaiswal595** [angular-ui/ui-sortable#536]
After adding touch punch (http://touchpunch.furf.com/)
Draggable worked in Only Android Devices.
But It's not working in IOS, IPad.
What needs to be done to make working it.

Please response ...

**Comment by thgreasi** [comment]
Does the [Simple Touch-Enabled Demo](https://codepen.io/thgreasi/pen/wzmvJv) (found in readme) work on your iOS devices?

**Comment by AdrianZielonka** [comment]
Just tested the link from @thgreasi on an iPad mini running iOS 10.3.1 without any issues.

**Comment by thgreasi** [comment]
Thanks for confirming @adrianzielonka

**Comment by ajaiswal595** [comment]
Yea It's working iPhone , but it is not working in  (IOS 10.3.3, Model MD511HN/A)
