### ISSUE TITLE
Select Multiple Drag

### ISSUE THREAD

**Issue by dashawk** [angular-ui/ui-sortable#540]
Hi,

I am trying to drag multiple items. Here is my current implementation.

[Using Native Code](https://codepen.io/dashawk/pen/ZXvdLE?editors=1010)
[Using Angular-Ui-Sortable](https://codepen.io/dashawk/pen/yzKzzp?editors=1010)

But it the angular app, its not working.

How can I achieve this using `angular-ui-sortable`?

**Comment by thgreasi** [comment]
You can use [ui-sortable-multiselection](https://github.com/thgreasi/ui-sortable-multiselection) and you can find an example in the README of this repo as well.

**Comment by dashawk** [comment]
Thanks for pointing me the right repo. I just have one more question. Can we install [ui-sortable-multiselection](https://github.com/thgreasi/ui-sortable-multiselection) via bower?

**Comment by thgreasi** [comment]
Yes, you should be able to do a `bower install angular-ui-sortable-multiselection`.
