### ISSUE TITLE
Draggable not working mobile

### ISSUE THREAD

**Issue by thisisirfan** [angular-ui/ui-sortable#544]
Can anyone help fixing item sorting in mobile, specifically in iphone. It's not working in iOS.

**Comment by thgreasi** [comment]
Hey, have you tried the Simple Touch-Enabled Demo found in README?

**Comment by thisisirfan** [comment]
Yes i have tested, it's also not working

**Comment by thisisirfan** [comment]
How can i integrate this jquery-ui-touch-punch lib with angular ?

**Comment by thisisirfan** [comment]
Hi, Sorry it was working, i think mixed it with some other example, so this example works in mobile fine:
https://codepen.io/thgreasi/pen/wzmvJv
