### ISSUE TITLE
version missing from bower.json for 0.18.0

### ISSUE THREAD

**Issue by senterright** [angular-ui/ui-sortable#546]
https://github.com/angular-ui/ui-sortable/blob/dff4e20cd60c8c16e5428dc7d8fd597fd07047f3/bower.json#L3

**Comment by thgreasi** [comment]
This is probably generated by angular-ui-publisher.
I think that the version field in bower.json isn't standardized and bower just relies to the tag version, and ended up removing the field before releasing 0.18.0 .
Does that cause issues to you @senterright ? If that's the case I guess I will add it back.

**Comment by senterright** [comment]
So for context, we're in the process of moving from angular 1.4 to 1.6, and bower to yarn, and eventually requirejs to webpack.

I think this is failing because we're using the "bower-away" stuff that's built into yarn that's trying to resolve `"@bower_components/angular-ui-sortable": "angular-ui/ui-sortable#~0.18.0"`.

i should be able to build with 0.17.x for the time being.

Thanks!
