### ISSUE TITLE
Broken Drag with Handle on Safari 11.0.3

### ISSUE THREAD

**Issue by BitForger** [angular-ui/ui-sortable#548]
I'm currently running into an issue with the ui sortable directive. When I click an hold on a handle in safari to move the section of the page it starts scrolling the page down on safari and it won't let me move it up. 
![large gif 1346x562](https://user-images.githubusercontent.com/7409480/36450557-ed13f448-1653-11e8-8578-86e0e234bc31.gif)

**Comment by thgreasi** [comment]
Oh, I hate weird Safari issues...
I would suggest you to try using the `placeholder` or the `helper` options to fill in the gap or use a smaller element while dragging (respectively).
Seems related to #495 #286 #109 , please check the discussion in there as well.

PS: I'm not a mac user, so someone else might have better ideas

**Comment by BitForger** [comment]
@thgreasi Are there docs for the placeholder and helper options? I don't see them

**Comment by BitForger** [comment]
Here is the snippet of the options that remedied the situation for me
```js
'ui-floating': true,
      start: function(e, ui) {
        $('.promo-list').sortable({
          sort: function(event, ui) {
            var $target = $(event.target);
            if (!/html|body/i.test($target.offsetParent()[0].tagName)) {
              var top = event.pageY - $target.offsetParent().offset().top - (ui.helper.outerHeight(true) / 2);
              ui.helper.css({'top' : top + 'px'});
            }
          }
        });

      },
      update: function(e, ui) {
        if (ui.item.sortable.model.idVideo == -1) {
          ui.item.sortable.cancel();
        }
      },
      scroll: false,
```
