### ISSUE TITLE
NPM repository doesn't have the latest version of ui-sortable

### ISSUE THREAD

**Issue by ricardomartins** [angular-ui/ui-sortable#550]
While transitoning my project from bower to webpack, I noticed that the latest version that npm provides is 0.18.0 instead of the 0.19.0 that is present in bower.
Don't know if this is supposed to be like this or if it was a mistake.

**Comment by thgreasi** [comment]
That's strange. Thanks for the heads-up, I will check it out tomorrow.

**Comment by thgreasi** [comment]
Published @ricardomartins , thanks for the heads-up :+1:

**Comment by ricardomartins** [comment]
You're welcome. Thanks for the quick reply and action. 👍
