### ISSUE TITLE
Incompatible with Jquery version 3.1.0

### ISSUE THREAD

**Issue by birladeanuadrian** [angular-ui/ui-sortable#555]
I tries to use it with jquery version 3.1.0, jquery ui 1.12.1, angularjs 1.6.8 and it did not work right. It worked after upgrading to jquery 3.3.1. The documentation should be updated to specify a higher version of jquery.

**Comment by thgreasi** [comment]
I think that something is wrong with your setup since the examples found in README work fine with jQuery 3.1.1
See: https://codepen.io/thgreasi/pen/wzmvJv
